/* LIQUIDEX FRAMEWORK — deep-tuned book across asset classes (equity / crypto / forex). Auto-generated. */
window.DEEP_BOOK = [
{
"sym": "XCUUSD",
"warn": true,
"pf": 9.149,
"dd": 6.25,
"win": 84.21,
"n": 38,
"arch": "comdty-confluence-long",
"remicro": false,
"assetClass": "equity",
"sector": "Commodity",
"family": "fade",
"status": "walk-forward",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R ON · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 10, target-R 3) · Wall-TP ON (min-room 0.3) · Partial-TP OFF",
"signals": "Iceberg ON (abs 7) · BSL/SSL ON (pool 2, exh-vol 2, eliq OFF) · Breaker OFF",
"gates": "LQX-gate OFF · Velo OFF",
"note": "OANDA:XCUUSD 4h copper STRONGEST comdty cell; LONG-ONLY fade+ice7+BSL2/2 wide buf10 = PF9.149/DD6.25/N38 84pct win; plateau buf8-10 identical (robust not spike); industrial-metal uptrend caught every dip; 84pct win + PF9 = clear BULL-REGIME ARTIFACT expect heavy OOS decay; walk-fwd MANDATORY; S=8.61",
"degen": false
},
{
"sym": "EURUSD",
"warn": false,
"pf": 8.057,
"dd": 2.28,
"win": 27.63,
"n": 76,
"arch": "forex-velo-both",
"remicro": false,
"assetClass": "forex",
"sector": "Forex",
"family": "both-direction",
"status": "ready",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts ON · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 15.1, target-R 3) · Wall-TP OFF · Partial-TP ON",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate OFF · Velo ON (plunge 0.3, window 4, dots 1)",
"note": "USER-CONFIG reproduced exact 8.057/2.28DD/76tr; REQUIRE-VELOCITY plunge0.3/win4 = the lever scan missed + buf15.1 + no-wall + PartialTP70/0.35 + cascRR3; both-dir; PF8 from ~21x avg-win-loss ratio (27pct win few big winners) high-variance; far beats scan 1.514; WALL-TP TOGGLE = PF dial: OFF (this config) = high-PF 8.057 trend-rider (winners run); ON+Skip = robust 3.8/56pct-win/100tr banker (lower PF higher consistency better OOS); walk-fwd before trust",
"degen": false
},
{
"sym": "DE",
"warn": true,
"pf": 5.748,
"dd": 23.62,
"win": 86.84,
"n": 76,
"arch": "fade-long",
"remicro": false,
"assetClass": "equity",
"sector": "Single-name",
"family": "fade",
"status": "walk-forward",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R ON · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 18, target-R 1) · Wall-TP ON (min-room 0.3) · Partial-TP ON",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate OFF · Velo OFF",
"note": "long-only clean-fade buf18; 1.37->5.75 BUT 87pct win = BULL-REGIME ARTIFACT (DE only uptrended 20-26); buy-dip works in-sample only; expect heavy OOS decay; WALK-FWD MANDATORY before any trust",
"degen": false
},
{
"sym": "AUDJPY",
"warn": false,
"pf": 4.898,
"dd": 7.58,
"win": 61.22,
"n": 49,
"arch": "forex-confluence-both",
"remicro": false,
"assetClass": "forex",
"sector": "Forex",
"family": "both-direction",
"status": "ready",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts ON · Require Min R:R ON · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 20, target-R 3) · Wall-TP ON (min-room 0.2) · Partial-TP OFF",
"signals": "Iceberg ON (abs 7) · BSL/SSL ON (pool 2, exh-vol 2, eliq OFF) · Breaker ON (vol 3)",
"gates": "LQX-gate OFF · Velo ON (plunge 0.95, window 5, dots 1)",
"note": "USER-CONFIG reproduced exact; my bare-fade gave 0.926 (GAVE UP TOO EARLY); REAL edge = ICEBERG7 + BSL2/2 + BREAKER3 confluence + REQUIRE-VELOCITY plunge0.95/win5 quality filter; both-dir 4.898/7.58DD/49tr/+26.58pct; 61pct win symmetric = trustworthy",
"degen": false
},
{
"sym": "DOGE",
"warn": true,
"pf": 4.759,
"dd": 4.29,
"win": 90.0,
"n": 40,
"arch": "crypto-fade-long",
"remicro": false,
"assetClass": "crypto",
"sector": "Crypto",
"family": "fade",
"status": "walk-forward",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 0.2, target-R 0.3) · Wall-TP OFF · Partial-TP ON",
"signals": "Iceberg OFF · BSL/SSL ON (pool 4, exh-vol 1.75, eliq OFF) · Breaker OFF",
"gates": "LQX-gate ON (maxLong 0.25, maxShort 1, veto 1) · Velo OFF",
"note": "BINANCE:DOGEUSDT 4h; LONG-ONLY FADE archetype (ETH/BTC family not crash-alt); seed buf0.35 3.391/6.37DD/N41 -> buffer TIGHTEN 0.35->0.2 the lever (PF 3.39->4.76 DD 6.37->4.29) buf0.1 4.626 plateau 0.1-0.2 buf1 worse; velocity ON thins N18 hurts; MaxLong 0.2 N34 lower; 90pct win long-only = bull-regime artifact walk-fwd MANDATORY; strongest cell this run S=4.563",
"degen": false
},
{
"sym": "NZDUSD",
"warn": true,
"pf": 4.657,
"dd": 6.01,
"win": 17.31,
"n": 52,
"arch": "forex-fade-short-cascstop",
"remicro": false,
"assetClass": "forex",
"sector": "Forex",
"family": "fade",
"status": "walk-forward",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 18, target-R 3) · Wall-TP ON (min-room 0.2) · Partial-TP OFF",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate OFF · Velo OFF",
"note": "OANDA:NZDUSD 4h SHORT-ONLY cascade-fade (like USDCHF the short side is the edge); both-dir marginal high-DD (buf23 1.125/DD12.66/N37 buf30 1.846/N27<floor); SHORT-ONLY HALVES DD + lifts PF (buf15 1.712/N60 buf18 4.657/DD6.01/N52 buf23 2.862/N18<floor); buf18 plateau center high N=52; 17.31pct win symmetric-ish trend-rider short side; short-only structural walk-fwd MANDATORY; S=4.393",
"degen": false
},
{
"sym": "GLD",
"warn": true,
"pf": 4.533,
"dd": 18.83,
"win": 82.81,
"n": 64,
"arch": "fade-long-ice",
"remicro": false,
"assetClass": "equity",
"sector": "ETF",
"family": "fade",
"status": "walk-forward",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R ON · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 22, target-R 1) · Wall-TP ON (min-room 0.3) · Partial-TP ON",
"signals": "Iceberg ON (abs 3) · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate OFF · Velo OFF",
"note": "long-only + ICEBERG(3) + buf22; iceberg=the GLD key (S1 hinted); 2.46->4.53; buf8=0.70 (needs wide); ice5 over-filters; 83pct win long-only = bull-regime walk-fwd mandatory",
"degen": false
},
{
"sym": "V",
"warn": true,
"pf": 4.443,
"dd": 25.45,
"win": 81.25,
"n": 80,
"arch": "fade-long",
"remicro": false,
"assetClass": "equity",
"sector": "Single-name",
"family": "fade",
"status": "walk-forward",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R ON · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 18, target-R 1) · Wall-TP ON (min-room 0.3) · Partial-TP ON",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate OFF · Velo OFF",
"note": "long-only clean-fade buf18 (plateau 18-25); shorts off (Visa uptrend); 1.36->4.44; +120pct PnL; 81pct win on 80tr; HIGH-PF walk-fwd critical",
"degen": false
},
{
"sym": "XOM",
"warn": true,
"pf": 4.386,
"dd": 20.63,
"win": 80.95,
"n": 42,
"arch": "fade-long-velo",
"remicro": false,
"assetClass": "equity",
"sector": "Single-name",
"family": "fade",
"status": "walk-forward",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R ON · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 12, target-R 1) · Wall-TP ON (min-room 0.3) · Partial-TP ON",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate OFF · Velo ON (plunge def, window def, dots def)",
"note": "long-only fade+velo wide buf12; energy wants wide buffer (buf3 2.04 -> buf8 3.66/16DD -> buf12 4.39/21DD); buf8=lower-DD alt; 81pct win regime-fit; 2.28->4.39 +85pct PnL",
"degen": false
},
{
"sym": "XAGUSD",
"warn": true,
"pf": 3.939,
"dd": 18.94,
"win": 75.0,
"n": 32,
"arch": "comdty-confluence-long",
"remicro": false,
"assetClass": "equity",
"sector": "Commodity",
"family": "fade",
"status": "walk-forward",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R ON · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 10, target-R 3) · Wall-TP ON (min-room 0.3) · Partial-TP OFF",
"signals": "Iceberg ON (abs 7) · BSL/SSL ON (pool 2, exh-vol 2, eliq OFF) · Breaker OFF",
"gates": "LQX-gate OFF · Velo OFF",
"note": "OANDA:XAGUSD 4h silver; LONG-ONLY fade+ice7+BSL2/2 (both-dir bled 0.96/N217 24pct win shorts whipsaw); WIDE buffer THE lever (gold-config buf7 1.24/DD17.7 -> buf10 3.939/DD18.9/N32 75pct win); plateau buf8-12 all S~3.3 (buf8 3.82/N33 buf12 3.94/N32); Breakeven flat; volatile DD~19pct one drawdown; 75pct win long-only bull-regime walk-fwd mandatory; S=3.312",
"degen": false
},
{
"sym": "COST",
"warn": true,
"pf": 3.851,
"dd": 22.96,
"win": 78.13,
"n": 64,
"arch": "fade-long",
"remicro": false,
"assetClass": "equity",
"sector": "Single-name",
"family": "fade",
"status": "walk-forward",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R ON · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 18, target-R 1) · Wall-TP ON (min-room 0.3) · Partial-TP ON",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate OFF · Velo OFF",
"note": "SHORTS OFF was the lever (secular uptrend; shorting rips bled to 0.75); long-only clean-fade buf18 (plateau 18-25); 1.39->3.85; +65pct; 78pct win; HIGH-PF on 64tr = walk-fwd critical",
"degen": false
},
{
"sym": "LRCX",
"warn": true,
"pf": 3.837,
"dd": 26.87,
"win": 83.33,
"n": 30,
"arch": "fade-long-cascstop",
"remicro": false,
"assetClass": "equity",
"sector": "Semis",
"family": "fade",
"status": "walk-forward",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 5, target-R 1) · Wall-TP ON (min-room 0.3) · Partial-TP OFF",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate ON (maxLong 0.5, maxShort 0.5, veto 0.85) · Velo OFF",
"note": "CascStop binds buffer; sweep buf5 = sharp peak (3.84/30) buf3 1.57/DD33 buf8 3.69/N26<floor; tight gates cut N to 18 no DD help; 83pct win + DD27pct = bull-regime artifact; walk-fwd mandatory",
"degen": false
},
{
"sym": "XLV",
"warn": true,
"pf": 3.798,
"dd": 10.52,
"win": 86.96,
"n": 46,
"arch": "gated-continuation-fade",
"remicro": false,
"assetClass": "equity",
"sector": "ETF",
"family": "trend/continuation",
"status": "walk-forward",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R ON · Cascade-Fade ONLY OFF",
"stops": "Stop-beyond-cascade OFF · Wall-TP ON (min-room 0.3) · Partial-TP OFF",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate ON (maxLong def, maxShort def, veto def) · Velo ON (plunge def, window def, dots def)",
"note": "buffer sweep 8 (plateau 8-11) on gated-continuation seed; clean-fade collapsed to N=10; buf18 N=16 too wide; seed-default 1.95/80 -> buf8 3.80/46; gates ON drive trade volume here (opposite of KO/TLT); 87pct win long-only = bull-regime walk-fwd mandatory",
"degen": false
},
{
"sym": "GBPUSD",
"warn": false,
"pf": 3.409,
"dd": 4.51,
"win": 25.81,
"n": 31,
"arch": "forex-fade-both-cascstop",
"remicro": false,
"assetClass": "forex",
"sector": "Forex",
"family": "both-direction",
"status": "ready",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts ON · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 23, target-R 3) · Wall-TP ON (min-room 0.2) · Partial-TP OFF",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate OFF · Velo OFF",
"note": "OANDA:GBPUSD 4h BOTH-DIR cascade-fade; STRONG; buffer the lever sharp zone (buf15 0.492/N100 buf20 0.448/N60 buf22 0.709/N43 buf23 2.67/N40 buf24 2.74/N22<floor buf25 2.066/N18); buf23 only N>=30 profit point; PARTIAL-TP OFF crumb lifted PF 2.67->3.41 same N31 DD4.51 (winners run); room0.4 over-filtered N2; 25.81pct win symmetric trend-rider; S=3.262",
"degen": false
},
{
"sym": "USDCAD",
"warn": false,
"pf": 3.264,
"dd": 3.74,
"win": 59.46,
"n": 74,
"arch": "forex-confluence-both",
"remicro": false,
"assetClass": "forex",
"sector": "Forex",
"family": "both-direction",
"status": "ready",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts ON · Require Min R:R ON · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 20, target-R 3) · Wall-TP ON (min-room 0.1) · Partial-TP ON",
"signals": "Iceberg ON (abs 10) · BSL/SSL ON (pool 2, exh-vol 2, eliq OFF) · Breaker ON (vol 6)",
"gates": "LQX-gate OFF · Velo ON (plunge 0.95, window 5, dots 1)",
"note": "USER-CONFIG reproduced exact; confluence ICEBERG10+BSL2/2+BREAKER6 + REQUIRE-VELOCITY 0.95/win5 + PartialTP 10/0.35 + room0.1; both-dir 3.264/3.74DD/74tr/+10.30pct; beats agent re-run 3.18; 59pct win symmetric low-DD = trustworthy",
"degen": false
},
{
"sym": "XLK",
"warn": true,
"pf": 3.184,
"dd": 11.73,
"win": 46.15,
"n": 39,
"arch": "fade-long-ice",
"remicro": false,
"assetClass": "equity",
"sector": "ETF",
"family": "fade",
"status": "walk-forward",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade OFF · Wall-TP ON (min-room 0.3) · Partial-TP OFF",
"signals": "Iceberg ON (abs 6) · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate ON (maxLong def, maxShort def, veto def) · Velo OFF",
"note": "fade seed buffer NON-BINDING (CascStop off); CascStop+buf18 bloated DD to 31pct N=11; real lever = Min iceberg absorption sweep 6 (plateau climbs 5->7 but N=31 cliff at 7); 2.39/69 seed -> abs6 3.18/39; long-only tech-ETF uptrend = walk-fwd mandatory",
"degen": false
},
{
"sym": "USDJPY",
"warn": false,
"pf": 3.03,
"dd": 9.7,
"win": 19.35,
"n": 31,
"arch": "forex-fade-both-cascstop",
"remicro": false,
"assetClass": "forex",
"sector": "Forex",
"family": "both-direction",
"status": "ready",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts ON · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 35, target-R 3) · Wall-TP ON (min-room 0.2) · Partial-TP OFF",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate OFF · Velo OFF",
"note": "OANDA:USDJPY 4h BOTH-DIR cascade-fade; needs WIDER buffer than GBP (JPY trends harder); buf23 0.931/N40 buf30 15.8/N21<floor buf35 3.03/N31 buf38 1.383/N26<floor; buf35 best N>=30 (N at floor); partial-ON 2.13/N29<floor lower; 19.35pct win symmetric trend-rider; N at floor fragile; S=2.762",
"degen": false
},
{
"sym": "WTICOUSD",
"warn": true,
"pf": 2.917,
"dd": 23.58,
"win": 66.67,
"n": 30,
"arch": "comdty-confluence-long-gated",
"remicro": false,
"assetClass": "equity",
"sector": "Commodity",
"family": "fade",
"status": "walk-forward",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R ON · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 12, target-R 3) · Wall-TP ON (min-room 0.3) · Partial-TP OFF",
"signals": "Iceberg ON (abs 7) · BSL/SSL ON (pool 2, exh-vol 2, eliq OFF) · Breaker OFF",
"gates": "LQX-gate ON (maxLong 0.45, maxShort def, veto 0.75) · Velo OFF",
"note": "OANDA:WTICOUSD 4h oil; both-dir fade bled 1.11/DD37.7/N257 24pct win (whipsaws); LONG-ONLY + WIDE buffer the lever (buf7 then buf12 2.251/DD23.7/N33 plateau 12-16 saturates); loose-LQX gate 0.45/0.75 lifts PF 2.25->2.92 without cutting N below floor (tight 0.3/0.6 N25 0.4/0.7 N29); gate does NOT cut DD (structural ~23.6pct); N=30 AT FLOOR fragile; 67pct win long-only bull-regime walk-fwd mandatory; S=2.361",
"degen": false
},
{
"sym": "AUDUSD",
"warn": false,
"pf": 2.796,
"dd": 7.13,
"win": 23.4,
"n": 47,
"arch": "forex-fade-both-cascstop",
"remicro": false,
"assetClass": "forex",
"sector": "Forex",
"family": "both-direction",
"status": "ready",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts ON · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 30, target-R 3) · Wall-TP ON (min-room 0.2) · Partial-TP OFF",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate OFF · Velo OFF",
"note": "OANDA:AUDUSD 4h BOTH-DIR cascade-fade; CLEAN plateau (best forex cell so far on robustness); buf23 2.153/N64 buf28 2.586/N51 buf30 2.796/N47 buf35 1.339/N43; buf30 plateau center high N=47 healthy margin; velocity-ON over-filtered N2; 23.40pct win symmetric trend-rider; S=2.610",
"degen": false
},
{
"sym": "ETH",
"warn": false,
"pf": 2.61,
"dd": 7.41,
"win": 87.5,
"n": 48,
"arch": "fade-bsl-cryptolong",
"remicro": false,
"assetClass": "crypto",
"sector": "Crypto",
"family": "fade",
"status": "ready",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R ON · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 0.35, target-R 0.3) · Wall-TP OFF · Partial-TP ON",
"signals": "Iceberg OFF · BSL/SSL ON (pool 4, exh-vol 1.75, eliq OFF) · Breaker OFF",
"gates": "LQX-gate ON (maxLong 0.25, maxShort 1, veto 1) · Velo OFF",
"note": "BITSTAMP:ETHUSD 4h USER-CONFIG; long-only cascade-fade + CascStop buf0.35 + BSL pool4/exh1.75 + LQX 0.25/1/1; REQUIRE-VELOCITY OFF (primary robust) = 2.61/7.41DD/48tr/+17.61pct. TOGGLE Require-velocity ON @ plunge0.95 -> 2.84/4.09DD/24tr full-range (or 3.665/3.20/20tr Mar24-Jun26) = higher PF lower DD but THIN N<30; samples-vs-quality knob; crypto bonus",
"degen": false
},
{
"sym": "SMH",
"warn": true,
"pf": 2.547,
"dd": 12.9,
"win": 58.65,
"n": 104,
"arch": "fade-long-wall-velo",
"remicro": false,
"assetClass": "equity",
"sector": "ETF",
"family": "fade",
"status": "walk-forward",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R ON · Cascade-Fade ONLY OFF",
"stops": "Stop-beyond-cascade ON (buffer 0.85, target-R 1) · Wall-TP ON (min-room 0.3) · Partial-TP ON",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate OFF · Velo ON (plunge def, window def, dots def)",
"note": "BATS feed (AMEX hangs); velo HALVED DD 27->13 (PF 2.82->2.55 but S better 2.26); long-only base+CascStop+WallTP+velo buf0.85; S1 4.84 was AMEX feed diff data",
"degen": false
},
{
"sym": "SOXX",
"warn": true,
"pf": 2.493,
"dd": 21.29,
"win": 54.76,
"n": 84,
"arch": "fade-bsl",
"remicro": false,
"assetClass": "equity",
"sector": "ETF",
"family": "fade",
"status": "walk-forward",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R ON · Cascade-Fade ONLY OFF",
"stops": "Stop-beyond-cascade ON (buffer 0.85, target-R 1) · Wall-TP OFF · Partial-TP ON",
"signals": "Iceberg OFF · BSL/SSL ON (pool 4, exh-vol 1.5, eliq OFF) · Breaker OFF",
"gates": "LQX-gate OFF · Velo OFF",
"note": "S1 config STANDS (CascStop+BSL fade); deep explored long-only fade-wall+velo 1.89/25 & base+BSL 1.80/25 but none beat S1 2.49/21; semis ETF high-DD",
"degen": false
},
{
"sym": "JPM",
"warn": false,
"pf": 2.452,
"dd": 18.45,
"win": 52.27,
"n": 44,
"arch": "equity-confluence-long",
"remicro": false,
"assetClass": "equity",
"sector": "Single-name",
"family": "fade",
"status": "ready",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R ON · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 5, target-R 3) · Wall-TP ON (min-room 0.3) · Partial-TP ON",
"signals": "Iceberg ON (abs 7) · BSL/SSL ON (pool 2, exh-vol 2, eliq OFF) · Breaker ON (vol 3)",
"gates": "LQX-gate OFF · Velo ON (plunge 0.95, window 5, dots 1)",
"note": "RE-RUN confluence-build flipped non-edge to 2.45 key=long-only+buf5+breaker-vol3; clean low-DD 18pct bank; breaker3 peak (vol4 N30-floor vol2 floods PF down)",
"degen": false
},
{
"sym": "SOL",
"warn": false,
"pf": 2.373,
"dd": 16.62,
"win": 19.87,
"n": 156,
"arch": "trend-both-dir",
"remicro": false,
"assetClass": "crypto",
"sector": "Crypto",
"family": "both-direction",
"status": "ready",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts ON · Require Min R:R ON · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade OFF · Wall-TP ON (min-room 0.2) · Partial-TP OFF",
"signals": "Iceberg ON (abs 10) · BSL/SSL ON (pool 4, exh-vol 1, eliq OFF) · Breaker ON (vol 4)",
"gates": "LQX-gate ON (maxLong 0.1, maxShort 0.35, veto 0.7) · Velo OFF",
"note": "BINANCE:SOLUSDT 4h USER-CONFIG; BOTH-DIRECTION trend-rider (19.87pct win + PF2.37 = small losses rare big winners); SHORTS ON the key - monetizes SOL crashes (long-only failed 0.5); Wall+Skip+Iceberg10+BSL4/1+Breaker4+tight-LQX 0.1/0.35/0.7; CascStop+Partial OFF; +294pct PnL 156tr; SYMMETRIC not bull-fit = trustworthy; crypto",
"degen": false
},
{
"sym": "GBPJPY",
"warn": false,
"pf": 2.352,
"dd": 8.47,
"win": 25.0,
"n": 80,
"arch": "forex-fade-both-cascstop",
"remicro": false,
"assetClass": "forex",
"sector": "Forex",
"family": "both-direction",
"status": "ready",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts ON · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 17, target-R 3) · Wall-TP ON (min-room 0.2) · Partial-TP OFF",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate OFF · Velo OFF",
"note": "OANDA:GBPJPY 4h BOTH-DIR cascade-fade; STRONG robust cell; clean buffer plateau (buf15 2.067/N100 buf17 2.352/DD8.47/N80 buf18 2.468/N59 buf23 1.178/N39); buf17 plateau center high N=80 robust (buf18 higher-S 2.251 but N59 - picked robust center); partial-ON lowers PF 2.013; 25pct win symmetric volatile-cross trend-rider; S=2.169",
"degen": false
},
{
"sym": "QQQ",
"warn": true,
"pf": 2.317,
"dd": 8.69,
"win": 46.88,
"n": 32,
"arch": "fade-long-wall",
"remicro": false,
"assetClass": "equity",
"sector": "ETF",
"family": "fade",
"status": "walk-forward",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade OFF · Wall-TP ON (min-room 0.5) · Partial-TP OFF",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate OFF · Velo ON (plunge def, window def, dots def)",
"note": "clean wall-fade buffer NON-BINDING (CascStop off); iceberg ON wrecked it (1.45/16pctDD); partial-TP cut winners (1.79); velo-off sturdier N45 but lower S; real lever = Min room to wall 0.5 (plateau 0.5-0.7) 2.20/34 -> 2.317/32; long-only QQQ uptrend = walk-fwd mandatory",
"degen": false
},
{
"sym": "ETN",
"warn": true,
"pf": 2.305,
"dd": 35.17,
"win": 76.67,
"n": 60,
"arch": "fade-long",
"remicro": false,
"assetClass": "equity",
"sector": "Single-name",
"family": "fade",
"status": "walk-forward",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R ON · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 18, target-R 1) · Wall-TP ON (min-room 0.3) · Partial-TP ON",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate OFF · Velo OFF",
"note": "long-only clean-fade buf18; 1.47->2.31 @ 35pct DD (caught 2020 crash dip); gate didnt cut DD; high-DD bull-regime; walk-fwd mandatory",
"degen": false
},
{
"sym": "IGV",
"warn": true,
"pf": 2.277,
"dd": 32.59,
"win": 89.13,
"n": 46,
"arch": "fade-long-wall",
"remicro": false,
"assetClass": "equity",
"sector": "ETF",
"family": "fade",
"status": "walk-forward",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R ON · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 8, target-R 1) · Wall-TP ON (min-room 0.3) · Partial-TP ON",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate OFF · Velo OFF",
"note": "long-only fade + CascStop buf8 peak; buf3 cuts DD 19 but PF1.2 lower S; 89pct win DD32pct bull-regime; software ETF",
"degen": false
},
{
"sym": "MPWR",
"warn": false,
"pf": 2.192,
"dd": 21.74,
"win": 46.15,
"n": 39,
"arch": "semi-fade-long-cascstop-bsl",
"remicro": false,
"assetClass": "equity",
"sector": "Semis",
"family": "fade",
"status": "ready",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 0.85, target-R 1) · Wall-TP OFF · Partial-TP OFF",
"signals": "Iceberg OFF · BSL/SSL ON (pool 4, exh-vol 1.75, eliq OFF) · Breaker OFF",
"gates": "LQX-gate OFF · Velo OFF",
"note": "JUICE2 BATS:MPWR plain-fade long-only; base-engine bleeds knives 0.64/N63; proven plain-fade+BSL pool4/exh1.75+CascStop-buf0.85 velo-off = 2.192/21.74DD/39tr; velo over-thins N19; iceberg7 flat; iceberg3 floods N77 but DD43 PF1.47 lower TRUST; clean N39 wins; prior 31tr/1.788; TRUST 0.726->1.170 strong deployable; 46pct win walk-fwd",
"degen": false
},
{
"sym": "XLE",
"warn": false,
"pf": 2.127,
"dd": 13.85,
"win": 37.7,
"n": 61,
"arch": "index-etf-fade-long-clean",
"remicro": false,
"assetClass": "equity",
"sector": "ETF",
"family": "fade",
"status": "ready",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade OFF · Wall-TP OFF · Partial-TP OFF",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate OFF · Velo OFF",
"note": "JUICE2 BATS:XLE energy-ETF gem clean cascade-fade long-only; CascFade-ONLY no-CascStop no-gate = 2.127/13.85DD/61tr clears N60; velocity over-thins now N23/2.882 (was the prior lever now hurts via data shift); CascStop+buf8 collapses N8/DD43; base-engine tight-LQX only 1.077/N94; clean fade wins; 38pct win; prior 37tr/2.941; TRUST 2.75->1.868 strong deployable high-sample low-DD; walk-fwd",
"degen": false
},
{
"sym": "MA",
"warn": false,
"pf": 2.109,
"dd": 9.43,
"win": 54.9,
"n": 51,
"arch": "index-fade-long-cascstop-wall",
"remicro": false,
"assetClass": "equity",
"sector": "Single-name",
"family": "fade",
"status": "ready",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 0.85, target-R 1) · Wall-TP ON (min-room 0.2) · Partial-TP ON",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate OFF · Velo OFF",
"note": "JUICE2 BATS:MA V-sibling clean uptrend long-only fade-wall+CascStop buf0.85 VERY LOW DD; 2.109/9.43DD/51tr; base-engine tight-LQX 1.36/16.58DD/N80 higher-N but lower TRUST; fade wins (lower DD higher PF); 55pct win; prior 33tr/2.383 thin now 51tr healthier; TRUST 2.0->1.638 strong deployable low-DD; walk-fwd",
"degen": false
},
{
"sym": "ETH-CB",
"warn": false,
"pf": 2.098,
"dd": 7.44,
"win": 86.15,
"n": 65,
"arch": "fade-crypto-ice-brk",
"remicro": false,
"assetClass": "crypto",
"sector": "Crypto",
"family": "fade",
"status": "ready",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R ON · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 0.35, target-R 0.3) · Wall-TP OFF · Partial-TP ON",
"signals": "Iceberg ON (abs 10) · BSL/SSL ON (pool 5, exh-vol 1.75, eliq OFF) · Breaker ON (vol 6)",
"gates": "LQX-gate ON (maxLong 0.25, maxShort 1, veto 1) · Velo OFF",
"note": "COINBASE:ETHUSD 4h USER-CONFIG; long-only fade + CascStop buf0.35 + ICEBERG10 + BSL pool5/exh1.75 + BREAKER6 + LQX 0.25/1/1; 2.098/7.44DD/65tr/+22.22pct; MORE robust than ETH-bitstamp (65 vs 48tr same DD); iceberg+breaker widen sample; crypto",
"degen": false
},
{
"sym": "BTC",
"warn": false,
"pf": 2.082,
"dd": 9.8,
"win": 44.66,
"n": 103,
"arch": "fade-breaker-BE",
"remicro": false,
"assetClass": "crypto",
"sector": "Crypto",
"family": "fade",
"status": "ready",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R ON · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade OFF · Wall-TP ON (min-room 0.2) · Partial-TP ON",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker ON (vol 4.5)",
"gates": "LQX-gate ON (maxLong 0.9, maxShort 0.55, veto 0.75) · Velo OFF",
"note": "BITSTAMP:BTCUSD 4h USER-CONFIG; long-only fade+wall+skip-no-room0.2+BREAKEVEN arm0.95+Breaker4.5+loose-LQX 0.9/0.55/0.75; partial 40/0.45; CascStop OFF; 44.66pct win+9.80DD = most robust cell in book (engine built for crypto microstructure); +59.91pct; CRYPTO bonus outside 50-equity set",
"degen": false
},
{
"sym": "DIA",
"warn": true,
"pf": 2.074,
"dd": 10.94,
"win": 41.94,
"n": 31,
"arch": "fade-long-wall",
"remicro": false,
"assetClass": "equity",
"sector": "ETF",
"family": "fade",
"status": "walk-forward",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade OFF · Wall-TP ON (min-room 0.5) · Partial-TP OFF",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate OFF · Velo OFF",
"note": "velo seed N=28<floor; dropped velo -> N32 2.02; Min room to wall 0.5 lifts to 2.07/31 (limited room headroom before N floor); partial-TP hurt (1.82); buffer non-binding; long-only Dow uptrend + N=31 near floor = walk-fwd mandatory",
"degen": false
},
{
"sym": "INTC",
"warn": true,
"pf": 2.053,
"dd": 46.6,
"win": 67.35,
"n": 49,
"arch": "fade-long-cascstop",
"remicro": false,
"assetClass": "equity",
"sector": "Semis",
"family": "fade",
"status": "walk-forward",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 3, target-R 1) · Wall-TP OFF · Partial-TP OFF",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate OFF · Velo OFF",
"note": "structural DOWNTRENDER; long-only only viable (both-dir 0.89/DD44 short-only 0.45); CascStop binds; buf3 = max S (2.053/DD46.6/N49) buf0.85 lower DD36.6 but PF1.12; buf5 DD56 buf15 N10; tight gate cuts DD46->39 but PF2.05->1.56 (S worse); DD46pct = MRVL-tier low quality; walk-fwd mandatory",
"degen": false
},
{
"sym": "TSM",
"warn": false,
"pf": 2.027,
"dd": 24.02,
"win": 40.24,
"n": 82,
"arch": "semi-robust-long",
"remicro": false,
"assetClass": "equity",
"sector": "Semis",
"family": "fade",
"status": "ready",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY OFF",
"stops": "Stop-beyond-cascade OFF · Wall-TP OFF · Partial-TP OFF",
"signals": "Iceberg ON (abs 3) · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate ON (maxLong 0.5, maxShort 0.39, veto 0.85) · Velo OFF",
"note": "JUICE2 BATS:TSM robust base-engine BIG WIN; prior 30tr/1.428 fade-wall thin; deployable = CascFade-OFF base + Iceberg3 + SkipCascade + loose-LQX 0.5/0.85 long-only = 2.027/24.02DD/82tr; tight-LQX0.3/0.6 hurt 1.875/DD30.6/N54; veto non-binding; clean robust cell TRUST 0.57->1.634 huge lift deployable not mirage; 40pct win",
"degen": false
},
{
"sym": "PEPE",
"warn": false,
"pf": 2.001,
"dd": 20.42,
"win": 37.5,
"n": 64,
"arch": "crypto-trend-both-dir",
"remicro": false,
"assetClass": "crypto",
"sector": "Crypto",
"family": "both-direction",
"status": "ready",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts ON · Require Min R:R OFF · Cascade-Fade ONLY OFF",
"stops": "Stop-beyond-cascade OFF · Wall-TP ON (min-room 0.2) · Partial-TP OFF",
"signals": "Iceberg ON (abs 10) · BSL/SSL ON (pool 4, exh-vol 1, eliq OFF) · Breaker ON (vol 4)",
"gates": "LQX-gate ON (maxLong 0.1, maxShort 0.35, veto 0.7) · Velo OFF",
"note": "JUICE2 BINANCE:PEPEUSDT both-dir trend-rider; KEY lever BrkVol 5->4 FLOODED sample 33->64tr (clears N60 floor) PF 2.468->2.001 DD 10.67->20.42 but TRUST 1.227->1.662 (N credit dominates); MaxShort tighten non-binding DD structural from longs; exh non-binding; thin 33tr/2.468 was mirage now deployable 64tr",
"degen": false
},
{
"sym": "KO",
"warn": false,
"pf": 1.979,
"dd": 19.75,
"win": 53.73,
"n": 201,
"arch": "fade-clean",
"remicro": false,
"assetClass": "equity",
"sector": "Single-name",
"family": "fade",
"status": "ready",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts ON · Require Min R:R ON · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 18, target-R 1) · Wall-TP ON (min-room 0.3) · Partial-TP ON",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate OFF · Velo OFF",
"note": "clean-fade buffer 18 (plateau 18-25); gates HURT (1.98->1.48); 1.17->1.98; +78pct PnL; low-vol consumer staple = sweet spot",
"degen": false
},
{
"sym": "AVAX",
"warn": false,
"pf": 1.976,
"dd": 20.84,
"win": 37.7,
"n": 61,
"arch": "crypto-trend-both-dir",
"remicro": false,
"assetClass": "crypto",
"sector": "Crypto",
"family": "both-direction",
"status": "ready",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts ON · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade OFF · Wall-TP ON (min-room 0.2) · Partial-TP OFF",
"signals": "Iceberg ON (abs 10) · BSL/SSL ON (pool 4, exh-vol 1, eliq OFF) · Breaker ON (vol 5)",
"gates": "LQX-gate ON (maxLong 0.1, maxShort 0.15, veto 0.7) · Velo OFF",
"note": "JUICE2 BINANCE:AVAXUSDT both-dir trend-rider; KEY lever BrkVol 6->5 FLOODED sample 37->61tr (clears N60 robustness floor) PF 1.91->1.976 DD flat 20.84; BrkVol4 over-floods N80 PF1.63; exh2 thins N47; MaxShort0.1 bloats DD27; prior 37tr/2.643 was thin-sample mirage TRUST 1.405->1.635 far more deployable; 38pct win symmetric",
"degen": false
},
{
"sym": "NXPI",
"warn": false,
"pf": 1.971,
"dd": 20.72,
"win": 65.57,
"n": 61,
"arch": "fade-gated",
"remicro": false,
"assetClass": "equity",
"sector": "Semis",
"family": "fade",
"status": "ready",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts ON · Require Min R:R ON · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 5, target-R 1) · Wall-TP ON (min-room 0.3) · Partial-TP ON",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate ON (maxLong 0.3, maxShort 0.3, veto 0.6) · Velo ON (plunge 0.25, window 5, dots 1)",
"note": "gate-tighten 0.4->0.3/veto0.6 DOUBLED PF 1.03->1.97 & halved DD 33->21; buffer 5 (semi vol); +99pct PnL; LQX thresholds = 3rd big lever",
"degen": false
},
{
"sym": "PANW",
"warn": true,
"pf": 1.957,
"dd": 22.99,
"win": 48.84,
"n": 86,
"arch": "fade-long-wall",
"remicro": false,
"assetClass": "equity",
"sector": "Single-name",
"family": "fade",
"status": "walk-forward",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R ON · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 1, target-R 1) · Wall-TP ON (min-room 0.3) · Partial-TP ON",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate OFF · Velo OFF",
"note": "long-only fade-wall buf1; 1.25->1.96 @ 23pct; buf3 2.18 but DD37 same S picked lower-DD; healthy 49pct win; cyber software",
"degen": false
},
{
"sym": "ON",
"warn": true,
"pf": 1.952,
"dd": 38.7,
"win": 63.16,
"n": 38,
"arch": "fade-long-cascstop-gated",
"remicro": false,
"assetClass": "equity",
"sector": "Semis",
"family": "fade",
"status": "walk-forward",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 3, target-R 1) · Wall-TP OFF · Partial-TP OFF",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate ON (maxLong 0.3, maxShort def, veto 0.6) · Velo OFF",
"note": "high-vol semi; CascStop binds buf; gate-RESCUED (NXPI-style not TSM-style); buf0.85 1.158/DD26.5 buf3 1.898/DD45.6; tight LQX 0.3/0.6 on buf3 CUTS DD45.6->38.7 AND raises PF to 1.952 (S1.41); 0.25/0.5 over-tightens N29<floor; buf0.85+gate clean DD20.7 but PF1.28 lower S; max-S = buf3+gate; DD38.7 walk-fwd mandatory",
"degen": false
},
{
"sym": "ICP",
"warn": true,
"pf": 1.89,
"dd": 27.06,
"win": 38.18,
"n": 55,
"arch": "crypto-confluence-long",
"remicro": false,
"assetClass": "crypto",
"sector": "Crypto",
"family": "fade",
"status": "walk-forward",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R ON · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 0.1, target-R 0.3) · Wall-TP ON (min-room 0.3) · Partial-TP OFF",
"signals": "Iceberg ON (abs 10) · BSL/SSL ON (pool 2, exh-vol 3, eliq OFF) · Breaker ON (vol 3)",
"gates": "LQX-gate ON (maxLong 0.1, maxShort 0.35, veto 0.7) · Velo OFF",
"note": "RE-RUN confluence-build flipped 0.95->1.89 key=long-only+iceberg10+exh3+buf0.1; AAVE-winning shape transferred (2021-launch alt sibling); buffer tighten 0.35->0.1 small crumb DD28->27; veto/exh4 non-binding; 38pct win long-only bull-regime walk-fwd mandatory",
"degen": false
},
{
"sym": "NATGASUSD",
"warn": false,
"pf": 1.882,
"dd": 9.97,
"win": 21.43,
"n": 56,
"arch": "comdty-trend-both-dir",
"remicro": false,
"assetClass": "equity",
"sector": "Commodity",
"family": "both-direction",
"status": "ready",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts ON · Require Min R:R OFF · Cascade-Fade ONLY OFF",
"stops": "Stop-beyond-cascade OFF · Wall-TP ON (min-room 0.2) · Partial-TP OFF",
"signals": "Iceberg ON (abs 10) · BSL/SSL ON (pool 4, exh-vol 1, eliq OFF) · Breaker ON (vol 6)",
"gates": "LQX-gate ON (maxLong 0.1, maxShort 0.5, veto 0.7) · Velo OFF",
"note": "OANDA:NATGASUSD 4h chronic downtrender; LONG-ONLY fade DD48pct (catches gas crashes 1.27/N35 77pct win low-quality); BOTH-DIR TREND-RIDER the edge (SOL pattern shorts monetize crashes 21pct win); fade-off+continuation+breaker+ice10+BSL4/1+tight-LQX; BrkVol6 HALVED DD 15.75->10.59 (plateau 6-8); MaxShort LOOSEN 0.35->0.5 lifts PF 1.82->1.88 DD->9.97 N56 (shorts=profit source dont kill); 21pct win symmetric trustworthy; S=1.711",
"degen": false
},
{
"sym": "AMD",
"warn": false,
"pf": 1.867,
"dd": 17.35,
"win": 52.0,
"n": 75,
"arch": "semi-robust-long-gated",
"remicro": false,
"assetClass": "equity",
"sector": "Semis",
"family": "fade",
"status": "ready",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY OFF",
"stops": "Stop-beyond-cascade OFF · Wall-TP OFF · Partial-TP OFF",
"signals": "Iceberg ON (abs 3) · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate ON (maxLong 0.3, maxShort 0.39, veto 0.6) · Velo OFF",
"note": "JUICE2 BATS:AMD robust base-engine HUGE WIN; prior fade-wall thin N32/1.515; CascFade-OFF + Iceberg3 + SkipCascade + tight-LQX 0.3/0.6 long-only = 1.867/17.35DD/75tr LOW DD; veto0.5 non-binding identical; base-engine fits AMD beautifully now (low DD high sample); 52pct win; TRUST 0.667->1.591 strongest semi cell deployable; walk-fwd",
"degen": false
},
{
"sym": "KLAC",
"warn": true,
"pf": 1.823,
"dd": 16.46,
"win": 41.18,
"n": 51,
"arch": "fade-long-wall",
"remicro": false,
"assetClass": "equity",
"sector": "Semis",
"family": "fade",
"status": "walk-forward",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade OFF · Wall-TP ON (min-room 0.3) · Partial-TP OFF",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate OFF · Velo OFF",
"note": "continuation seed breaker floods 270tr DD31pct; same semi pattern -> fade-wall gates-off best 1.82/DD16/N51; iceberg flat PF but +DD (1.83/DD20); room non-binding; healthy N; long-only walk-fwd mandatory",
"degen": false
},
{
"sym": "IWM",
"warn": false,
"pf": 1.795,
"dd": 24.61,
"win": 40.2,
"n": 102,
"arch": "equity-confluence-long",
"remicro": false,
"assetClass": "equity",
"sector": "ETF",
"family": "fade",
"status": "ready",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R ON · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 3, target-R 3) · Wall-TP ON (min-room 0.3) · Partial-TP ON",
"signals": "Iceberg ON (abs 7) · BSL/SSL ON (pool 2, exh-vol 2, eliq OFF) · Breaker ON (vol 2)",
"gates": "LQX-gate OFF · Velo ON (plunge 0.95, window 5, dots 1)",
"note": "RE-RUN confluence-build flipped non-edge 0.98->1.80 key=long-only+tight-buf3+breaker-vol2; low breaker thresh flooded N 29->102 with quality; DD healthy 24.6pct",
"degen": false
},
{
"sym": "SCHD",
"warn": false,
"pf": 1.768,
"dd": 4.65,
"win": 57.35,
"n": 68,
"arch": "index-etf-robust-long-gated",
"remicro": false,
"assetClass": "equity",
"sector": "ETF",
"family": "fade",
"status": "ready",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY OFF",
"stops": "Stop-beyond-cascade OFF · Wall-TP OFF · Partial-TP OFF",
"signals": "Iceberg ON (abs 5) · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate ON (maxLong 0.4, maxShort 0.39, veto 0.7) · Velo OFF",
"note": "JUICE2 BATS:SCHD div-ETF robust base-engine VERY LOW DD; prior 35tr/2.047 clean-fade thin; deployable = CascFade-OFF base + Iceberg5 + SkipCascade + mid-LQX 0.4/0.7 long-only = 1.768/4.65DD/68tr clears N60; loose-LQX 0.5/0.85 1.595/9.09DD/N78 (TRUST 1.462); tight 0.3/0.6 1.743/4.01DD/N51 (TRUST 1.424); mid 0.4/0.7 best TRUST 1.690 N>=60 lowest-S-DD combo; 57pct win; TRUST 1.119->1.690 strong deployable; walk-fwd",
"degen": false
},
{
"sym": "RENDER",
"warn": true,
"pf": 1.757,
"dd": 14.38,
"win": 85.71,
"n": 70,
"arch": "crypto-fade-long",
"remicro": false,
"assetClass": "crypto",
"sector": "Crypto",
"family": "fade",
"status": "walk-forward",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 0.6, target-R 0.3) · Wall-TP OFF · Partial-TP ON",
"signals": "Iceberg OFF · BSL/SSL ON (pool 4, exh-vol 1.75, eliq OFF) · Breaker OFF",
"gates": "LQX-gate ON (maxLong 0.25, maxShort 1, veto 1) · Velo OFF",
"note": "BINANCE:RENDERUSDT 4h; LONG-ONLY FADE archetype but wants WIDE buffer (opposite of DOGE); seed buf0.35 1.437/16.11DD/N70 -> buffer WIDEN 0.5=1.717 0.6=1.757 0.75=1.959/DD16.7 (higher S) but cliff at 0.85 (DD30) so picked 0.6 mid-plateau for robustness; buf0.2 worse; 86pct win long-only bull-regime walk-fwd MANDATORY; S=1.536 (buf0.75 S1.68 if aggressive)",
"degen": false
},
{
"sym": "DE30EUR",
"warn": true,
"pf": 1.741,
"dd": 11.41,
"win": 68.12,
"n": 69,
"arch": "index-confluence-long",
"remicro": false,
"assetClass": "equity",
"sector": "Index",
"family": "fade",
"status": "walk-forward",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R ON · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 7, target-R 3) · Wall-TP ON (min-room 0.3) · Partial-TP OFF",
"signals": "Iceberg ON (abs 7) · BSL/SSL ON (pool 2, exh-vol 1, eliq OFF) · Breaker OFF",
"gates": "LQX-gate OFF · Velo OFF",
"note": "OANDA:DE30EUR 4h German DAX (DE40EUR HUNG the recompute - tester stuck updating-true 15s+ like MATIC; used DE30EUR fallback per nodata rule); LONG-ONLY fade+ice7+BSL exh1; buf7 peak 1.741/DD11.4/N69 robust-N (wide plateau 7-12 ~1.7 buf5 1.59); 68pct win long-only bull-regime walk-fwd mandatory; S=1.563",
"degen": false
},
{
"sym": "ARM",
"warn": true,
"pf": 1.728,
"dd": 31.55,
"win": 38.81,
"n": 67,
"arch": "semi-robust-long-breaker",
"remicro": false,
"assetClass": "equity",
"sector": "Semis",
"family": "fade",
"status": "walk-forward",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY OFF",
"stops": "Stop-beyond-cascade OFF · Wall-TP OFF · Partial-TP OFF",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker ON (vol 2)",
"gates": "LQX-gate OFF · Velo OFF",
"note": "JUICE2 BATS:ARM recent-IPO volatile semi; base-engine CascFade-OFF + Breaker-vol2 long-only floods sample N67 clears robustness floor; prior continuation-breaker 114tr/1.366 no longer reproduces (data shift N now 43-67); BrkVol2 1.728/31.55DD/67tr beats BrkVol3 2.106/N43 on TRUST; tight-LQX strangles to N6 (recent-IPO thin); gate doesnt cut DD (TSM/AMD pattern); Breakeven hurt; DD structural 31pct; TRUST 1.038->1.314 deployable high-sample; walk-fwd high-DD",
"degen": false
},
{
"sym": "UNI",
"warn": true,
"pf": 1.703,
"dd": 19.02,
"win": 47.5,
"n": 40,
"arch": "crypto-fade-long",
"remicro": false,
"assetClass": "crypto",
"sector": "Crypto",
"family": "fade",
"status": "walk-forward",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 0.65, target-R 0.3) · Wall-TP ON (min-room 0.2) · Partial-TP ON",
"signals": "Iceberg OFF · BSL/SSL ON (pool 4, exh-vol 1.75, eliq OFF) · Breaker OFF",
"gates": "LQX-gate ON (maxLong 0.2, maxShort 1, veto 1) · Velo OFF",
"note": "BINANCE:UNIUSDT 4h; LONG-ONLY FADE archetype clears PF1; 2020-launch alt with real history; seed buf0.35 1.323/20.49DD/N46 -> buffer WIDEN the lever (opposite of DOGE) buf0.5 1.47 buf0.75 1.646 buf0.65 peak 1.703/19.02DD; buf1 1.508 buf0.2 1.12; MaxLong tighten 0.25->0.2 small crumb (0.15 N-floor); exh2.5/room0.35/pool5 all worse; both-dir trend-rider not needed (fade clears); 47.5pct win healthy; S=1.431 walk-fwd MANDATORY",
"degen": false
},
{
"sym": "ARB",
"warn": false,
"pf": 1.677,
"dd": 19.58,
"win": 21.43,
"n": 56,
"arch": "crypto-trend-both-dir",
"remicro": false,
"assetClass": "crypto",
"sector": "Crypto",
"family": "both-direction",
"status": "ready",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts ON · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade OFF · Wall-TP ON (min-room 0.2) · Partial-TP OFF",
"signals": "Iceberg ON (abs 10) · BSL/SSL ON (pool 4, exh-vol 3, eliq OFF) · Breaker ON (vol 8)",
"gates": "LQX-gate ON (maxLong 0.1, maxShort 0.35, veto 0.7) · Velo OFF",
"note": "BINANCE:ARBUSDT 4h; downtrender; long-only fade 0.788/19.32DD/N48 sub-1; BOTH-DIR trend-rider edge; seed BrkVol5/exh3 1.276/23.93DD/N63 -> BrkVol sweep the lever 6=1.298 7=1.424 8=1.677/19.58DD (plateau 8-10); MaxShort tighten 0.25 kills shorts (downtrender) loose 0.5 flat; S=1.402 symmetric",
"degen": false
},
{
"sym": "JUP",
"warn": false,
"pf": 1.67,
"dd": 25.79,
"win": 34.09,
"n": 44,
"arch": "crypto-fade-long",
"remicro": false,
"assetClass": "crypto",
"sector": "Crypto",
"family": "fade",
"status": "ready",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 0.2, target-R 0.3) · Wall-TP ON (min-room 0.2) · Partial-TP ON",
"signals": "Iceberg OFF · BSL/SSL ON (pool 4, exh-vol 1, eliq OFF) · Breaker OFF",
"gates": "LQX-gate ON (maxLong 0.25, maxShort 1, veto 1) · Velo OFF",
"note": "BINANCE:JUPUSDT 4h LONG-ONLY FADE archetype (trend-rider worse 0.86/DD44); buffer non-binding (0.35 vs 0.2 identical ~1.39); KEY = Exhaustion-vol LOOSEN 1.75->1 grew N 36->44 lifted PF 1.39->1.67; velocity over-thinned N14; MaxLong tighten 0.2 N30-floor 0.15 N18; kept 0.25 for N margin (44); DD~25.8pct structural; 34pct win; S=1.327 walk-fwd recommended",
"degen": false
},
{
"sym": "XLP",
"warn": false,
"pf": 1.653,
"dd": 8.58,
"win": 53.33,
"n": 75,
"arch": "index-etf-robust-long-gated",
"remicro": false,
"assetClass": "equity",
"sector": "ETF",
"family": "fade",
"status": "ready",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY OFF",
"stops": "Stop-beyond-cascade OFF · Wall-TP OFF · Partial-TP OFF",
"signals": "Iceberg ON (abs 5) · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate ON (maxLong 0.3, maxShort 0.39, veto 0.6) · Velo OFF",
"note": "JUICE2 BATS:XLP staples-ETF robust base-engine VERY LOW DD; CascFade-OFF + Iceberg-hits5 + SkipCascade + tight-LQX 0.3/0.6 long-only = 1.653/8.58DD/75tr; KEY IceHits 3->5 (1.179->1.653); IceHits7 1.428/N59; clean low-DD; prior 48tr/1.327 fade-cascstop; 53pct win; TRUST 0.92->1.522 strong deployable high-sample low-DD; walk-fwd",
"degen": false
},
{
"sym": "MU",
"warn": false,
"pf": 1.63,
"dd": 32.96,
"win": 47.25,
"n": 91,
"arch": "semi-robust-long",
"remicro": false,
"assetClass": "equity",
"sector": "Semis",
"family": "fade",
"status": "ready",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY OFF",
"stops": "Stop-beyond-cascade OFF · Wall-TP OFF · Partial-TP OFF",
"signals": "Iceberg ON (abs 5) · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate ON (maxLong 0.5, maxShort 0.39, veto 0.85) · Velo OFF",
"note": "JUICE2 BATS:MU robust base-engine BIG WIN; prior 31tr/1.239 plain-fade thin; CascFade-OFF + Iceberg-hits5 + loose-LQX 0.5/0.85 long-only skip-OFF = 1.630/32.96DD/91tr; KEY levers SkipCascade OFF (1.216->1.274) then IceHits 3->5 (1.274->1.630 cut DD 41->33); IceHits7 over-filters 1.138/45DD; tight-LQX hurt 0.962/49DD (TSM/AMD pattern); 47pct win; TRUST 0.74->1.226 strong deployable high-sample; walk-fwd",
"degen": false
},
{
"sym": "BNB",
"warn": false,
"pf": 1.605,
"dd": 19.69,
"win": 25.68,
"n": 74,
"arch": "crypto-confluence-both",
"remicro": false,
"assetClass": "crypto",
"sector": "Crypto",
"family": "both-direction",
"status": "ready",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts ON · Require Min R:R ON · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 0.35, target-R 3) · Wall-TP ON (min-room 0.3) · Partial-TP OFF",
"signals": "Iceberg ON (abs 7) · BSL/SSL ON (pool 2, exh-vol 2, eliq OFF) · Breaker ON (vol 6)",
"gates": "LQX-gate OFF · Velo ON (plunge 0.95, window 5, dots 1)",
"note": "RE-RUN confluence-build flipped 0.86->1.61 key=both-dir-trend-rider+breaker-vol6; full stack fade+ice7+bsl2/2+breaker+velo; breaker-vol sweep the lever 3=1.02 5=1.48 6=1.61 8=1.56; tight-LQX HURT exh2 best exh1-floods exh3-thins; 25pct win symmetric",
"degen": false
},
{
"sym": "PEP",
"warn": false,
"pf": 1.595,
"dd": 6.47,
"win": 48.6,
"n": 107,
"arch": "fade-both",
"remicro": false,
"assetClass": "equity",
"sector": "Single-name",
"family": "both-direction",
"status": "ready",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts ON · Require Min R:R ON · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 0.85, target-R 3) · Wall-TP OFF · Partial-TP ON",
"signals": "Iceberg ON (abs 5) · BSL/SSL ON (pool 2, exh-vol 4, eliq OFF) · Breaker ON (vol 7.5)",
"gates": "LQX-gate ON (maxLong 0.5, maxShort 0.15, veto 0.75) · Velo ON (plunge 0.5, window 12, dots 1)",
"note": "user-config reproduced exactly",
"degen": false
},
{
"sym": "XRP",
"warn": false,
"pf": 1.587,
"dd": 19.0,
"win": 13.79,
"n": 87,
"arch": "crypto-trend-both-dir",
"remicro": false,
"assetClass": "crypto",
"sector": "Crypto",
"family": "both-direction",
"status": "ready",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts ON · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade OFF · Wall-TP ON (min-room 0.2) · Partial-TP OFF",
"signals": "Iceberg ON (abs 10) · BSL/SSL ON (pool 4, exh-vol 1, eliq OFF) · Breaker ON (vol 6)",
"gates": "LQX-gate ON (maxLong 0.1, maxShort 0.35, veto 0.7) · Velo OFF",
"note": "BINANCE:XRPUSDT 4h; long-only fade FAILED 0.677/11.87DD/N54 highwin (crash-prone alt); BOTH-DIR trend-rider clears PF1 (SOL pattern shorts monetize XRP crashes 13.79pct win); seed 1.201/23.59DD/N125 -> BrkVol sweep 4->6 the lever (PF 1.20->1.32->1.587 DD down to 19.00) BrkVol8 over-filters; MaxShort 0.25 hurt 0.5 flat; veto/room/iceberg/MaxLong all flat-or-worse; S=1.334 symmetric not bull-fit",
"degen": false
},
{
"sym": "TSEM",
"warn": true,
"pf": 1.582,
"dd": 19.19,
"win": 43.59,
"n": 39,
"arch": "continuation-long-wall",
"remicro": false,
"assetClass": "equity",
"sector": "Semis",
"family": "trend/continuation",
"status": "walk-forward",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY OFF",
"stops": "Stop-beyond-cascade OFF · Wall-TP ON (min-room 0.3) · Partial-TP OFF",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate OFF · Velo OFF",
"note": "TRENDER like XLI; fade thin (long-only N19 PF0.65 / both-dir N28 PF0.90 both <floor); continuation+breaker floods N305 DD41pct; KEY = continuation-WALL (breaker off + Target-OB on) long-only = 1.582/DD19.2/N39; room0.5 worse; shorts-on 0.999/DD38; gates dont help; clean low-DD trender",
"degen": false
},
{
"sym": "SPY",
"warn": false,
"pf": 1.571,
"dd": 16.6,
"win": 44.26,
"n": 61,
"arch": "index-etf-robust-long-gated",
"remicro": false,
"assetClass": "equity",
"sector": "ETF",
"family": "fade",
"status": "ready",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY OFF",
"stops": "Stop-beyond-cascade OFF · Wall-TP OFF · Partial-TP OFF",
"signals": "Iceberg ON (abs 5) · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate ON (maxLong 0.4, maxShort 0.39, veto 0.7) · Velo OFF",
"note": "JUICE2 BATS:SPY S&P500-ETF robust base-engine; prior 32tr/1.521 wall-fade thin; deployable = CascFade-OFF base + Iceberg5 + mid-LQX 0.4/0.7 long-only; KEY lever SkipCascade OFF lifted PF 1.428->1.571 cut DD 18.76->16.60 grew N 58->61; tight-LQX 0.3/0.6 1.600/18.41DD/N50 (TRUST 1.126); SkipCascade-OFF best TRUST 1.347 N>=60; 44pct win; TRUST 1.121->1.347 deployable high-sample; walk-fwd",
"degen": false
},
{
"sym": "AAVE",
"warn": true,
"pf": 1.565,
"dd": 24.4,
"win": 23.33,
"n": 90,
"arch": "crypto-confluence-long",
"remicro": false,
"assetClass": "crypto",
"sector": "Crypto",
"family": "fade",
"status": "walk-forward",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R ON · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 0.35, target-R 0.3) · Wall-TP ON (min-room 0.3) · Partial-TP OFF",
"signals": "Iceberg ON (abs 10) · BSL/SSL ON (pool 2, exh-vol 3, eliq OFF) · Breaker ON (vol 3)",
"gates": "LQX-gate ON (maxLong 0.1, maxShort 0.35, veto 0.7) · Velo OFF",
"note": "RE-RUN confluence-build flipped 0.82->1.57 key=long-only+iceberg-hits10+exhaustion-vol3; both-dir bled shorts dragged PF<1; long-only 1.17 -> ice10+exh3 crumb lifted to 1.565 DD24; tight-LQX helped; breaker6 thins below floor; DeFi blue-chip walk-fwd mandatory",
"degen": false
},
{
"sym": "NAS100USD",
"warn": true,
"pf": 1.54,
"dd": 12.53,
"win": 58.06,
"n": 31,
"arch": "index-confluence-long",
"remicro": false,
"assetClass": "equity",
"sector": "Index",
"family": "fade",
"status": "walk-forward",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R ON · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 6, target-R 3) · Wall-TP ON (min-room 0.3) · Partial-TP OFF",
"signals": "Iceberg ON (abs 7) · BSL/SSL ON (pool 2, exh-vol 2, eliq OFF) · Breaker OFF",
"gates": "LQX-gate OFF · Velo OFF",
"note": "OANDA:NAS100USD 4h Nasdaq tech-heavy uptrender; LONG-ONLY fade+ice7+BSL2/2; wants slightly wider buf than SPX (buf5 1.349/N32 buf7 1.721/N29<floor buf6 1.540/DD12.5/N31 best N>=30); buf10 N28<floor; breaker FLOODS 106tr PF0.90 (continuation bleeds); 58pct win long-only bull-regime walk-fwd mandatory; S=1.369",
"degen": false
},
{
"sym": "NVDA",
"warn": false,
"pf": 1.517,
"dd": 36.27,
"win": 53.13,
"n": 64,
"arch": "semi-robust-long-gated",
"remicro": false,
"assetClass": "equity",
"sector": "Semis",
"family": "fade",
"status": "ready",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY OFF",
"stops": "Stop-beyond-cascade OFF · Wall-TP OFF · Partial-TP OFF",
"signals": "Iceberg ON (abs 3) · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate ON (maxLong 0.3, maxShort 0.39, veto 0.6) · Velo OFF",
"note": "JUICE2 BATS:NVDA robust base-engine BIG WIN; prior continuation N222/1.185; CascFade-OFF + Iceberg3 + SkipCascade + tight-LQX 0.3/0.6 long-only = 1.517/36.27DD/64tr clears N60; tighter 0.25/0.5 worse 1.176/46DD (gate doesnt cut DD TSM/AMD pattern); DD structural 36pct high-vol semi; 53pct win; TRUST 0.884->1.113 deployable; walk-fwd high-DD",
"degen": false
},
{
"sym": "DOT",
"warn": false,
"pf": 1.503,
"dd": 14.74,
"win": 31.43,
"n": 105,
"arch": "crypto-trend-both-dir",
"remicro": false,
"assetClass": "crypto",
"sector": "Crypto",
"family": "both-direction",
"status": "ready",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts ON · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade OFF · Wall-TP ON (min-room 0.2) · Partial-TP OFF",
"signals": "Iceberg ON (abs 10) · BSL/SSL ON (pool 4, exh-vol 2, eliq OFF) · Breaker ON (vol 5)",
"gates": "LQX-gate ON (maxLong 0.1, maxShort 0.35, veto 0.7) · Velo OFF",
"note": "JUICE2 BINANCE:DOTUSDT both-dir trend-rider; KEY lever BrkVol 4->5 (data shifted) lifted PF 1.445->1.503 AND HALVED DD 21.85->14.74 N105; BrkVol6 drops PF1.24; MaxShort0.5 floods N137 but lower S 1.218; was DOT-marginal high-DD now clean robust cell TRUST 1.057->1.310",
"degen": false
},
{
"sym": "ENA",
"warn": false,
"pf": 1.5,
"dd": 15.7,
"win": 25.53,
"n": 47,
"arch": "crypto-trend-both-dir",
"remicro": false,
"assetClass": "crypto",
"sector": "Crypto",
"family": "both-direction",
"status": "ready",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts ON · Require Min R:R ON · Cascade-Fade ONLY OFF",
"stops": "Stop-beyond-cascade OFF · Wall-TP ON (min-room 0.2) · Partial-TP OFF",
"signals": "Iceberg ON (abs 10) · BSL/SSL ON (pool 4, exh-vol 1, eliq OFF) · Breaker ON (vol 8)",
"gates": "LQX-gate ON (maxLong 0.1, maxShort 0.25, veto 0.7) · Velo OFF",
"note": "BINANCE:ENAUSDT 4h 2024-launch downtrender; long-only fade 0.685/DD54; BOTH-DIR trend-rider edge; KEY = BrkVol8 + MaxShort TIGHTEN 0.35->0.25 cut DD 49.6->15.7 lifted PF 0.88->1.50; BrkVol10 worse 1.15 MaxShort0.2 N33 lower; 25.5pct win symmetric; S=1.296 recommended",
"degen": false
},
{
"sym": "INJ",
"warn": true,
"pf": 1.461,
"dd": 12.05,
"win": 84.62,
"n": 52,
"arch": "crypto-fade-long",
"remicro": false,
"assetClass": "crypto",
"sector": "Crypto",
"family": "fade",
"status": "walk-forward",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 0.1, target-R 0.3) · Wall-TP OFF · Partial-TP ON",
"signals": "Iceberg OFF · BSL/SSL ON (pool 4, exh-vol 2.5, eliq OFF) · Breaker OFF",
"gates": "LQX-gate ON (maxLong 0.25, maxShort 1, veto 1) · Velo OFF",
"note": "BINANCE:INJUSDT 4h; LONG-ONLY FADE archetype; seed buf0.35 1.309/16.35DD/N66 -> buffer tighten 0.35->0.1 (PF up DD down) plateau 0.05-0.1; KEY 2nd lever = Exhaustion volume 1.75->2.5 cuts DD 15.47->12.05 (exh3.5 PF collapses); 85pct win long-only bull-regime walk-fwd MANDATORY; S=1.304",
"degen": false
},
{
"sym": "XLF",
"warn": false,
"pf": 1.454,
"dd": 14.12,
"win": 51.92,
"n": 52,
"arch": "financial-etf-robust-long-gated",
"remicro": true,
"assetClass": "equity",
"sector": "ETF",
"family": "fade",
"status": "re-microtune",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY OFF",
"stops": "Stop-beyond-cascade OFF · Wall-TP OFF · Partial-TP OFF",
"signals": "Iceberg ON (abs 5) · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate ON (maxLong 0.3, maxShort 0.39, veto 0.6) · Velo OFF",
"note": "JUICE2 BATS:XLF FLIPS prior non-edge (financials misfit DD>=36pct); §2c base-engine RESCUE = CascFade-OFF base + Iceberg5 + SkipCascade + tight-LQX 0.3/0.6 long-only = 1.454/14.12DD/52tr (prior best fade was 0.895/36DD); mid-LQX 0.4/0.7 1.174/17.59DD/N70 lower TRUST (worse trades in); tight gate cleans + halves DD; 52pct win; TRUST 0(non-edge)->1.105 deployable; walk-fwd",
"degen": false
},
{
"sym": "NEAR",
"warn": true,
"pf": 1.454,
"dd": 8.42,
"win": 80.0,
"n": 50,
"arch": "crypto-fade-long",
"remicro": false,
"assetClass": "crypto",
"sector": "Crypto",
"family": "fade",
"status": "walk-forward",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 0.2, target-R 0.3) · Wall-TP OFF · Partial-TP ON",
"signals": "Iceberg OFF · BSL/SSL ON (pool 4, exh-vol 1.75, eliq OFF) · Breaker OFF",
"gates": "LQX-gate ON (maxLong 0.25, maxShort 1, veto 1) · Velo OFF",
"note": "BINANCE:NEARUSDT 4h; LONG-ONLY FADE archetype clears PF1; seed buf0.35 1.508/19.25DD/N50 -> buffer TIGHTEN 0.35->0.2 HALVES DD (19.25->8.42) the lever; buf0.5 higher PF1.526 but DD19.4 lower S; buf0.1 plateau; MaxLong 0.2 cuts N; 80pct win long-only = bull-regime walk-fwd MANDATORY; S=1.341",
"degen": false
},
{
"sym": "XLI",
"warn": false,
"pf": 1.453,
"dd": 21.92,
"win": 47.22,
"n": 72,
"arch": "index-etf-robust-long-gated",
"remicro": true,
"assetClass": "equity",
"sector": "ETF",
"family": "fade",
"status": "re-microtune",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY OFF",
"stops": "Stop-beyond-cascade OFF · Wall-TP OFF · Partial-TP OFF",
"signals": "Iceberg ON (abs 3) · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate ON (maxLong 0.3, maxShort 0.39, veto 0.6) · Velo OFF",
"note": "JUICE2 BATS:XLI industrials-ETF was stubborn-trender; base-engine NOW takes it (data shift); CascFade-OFF + Iceberg3 + SkipCascade + tight-LQX 0.3/0.6 long-only = 1.453/21.92DD/72tr clears N60; loose-LQX 1.322/23.73DD/N115 lower TRUST; prior continuation-wall 50tr/1.298; tight-gate base wins; 47pct win; TRUST 1.1->1.192 deployable robust; walk-fwd",
"degen": false
},
{
"sym": "MRVL",
"warn": true,
"pf": 1.447,
"dd": 44.23,
"win": 37.93,
"n": 58,
"arch": "semi-confluence-long-gated",
"remicro": true,
"assetClass": "equity",
"sector": "Semis",
"family": "fade",
"status": "re-microtune",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R ON · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 5, target-R 3) · Wall-TP ON (min-room 0.3) · Partial-TP ON",
"signals": "Iceberg ON (abs 7) · BSL/SSL ON (pool 2, exh-vol 2, eliq OFF) · Breaker ON (vol 3)",
"gates": "LQX-gate ON (maxLong 0.3, maxShort 0.3, veto 0.6) · Velo ON (plunge 0.95, window 5, dots 1)",
"note": "RE-RUN confluence-build flipped non-edge to 1.45 key=long-only+tight-LQX-0.3/veto0.6+breaker3; gate HELPED (unlike AMAT) DD structurally high 44pct semi",
"degen": false
},
{
"sym": "LTC",
"warn": false,
"pf": 1.433,
"dd": 25.77,
"win": 24.29,
"n": 70,
"arch": "crypto-confluence-both",
"remicro": false,
"assetClass": "crypto",
"sector": "Crypto",
"family": "both-direction",
"status": "ready",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts ON · Require Min R:R ON · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 0.2, target-R 8) · Wall-TP ON (min-room 0.3) · Partial-TP ON",
"signals": "Iceberg ON (abs 5) · BSL/SSL ON (pool 2, exh-vol 2, eliq OFF) · Breaker ON (vol 8)",
"gates": "LQX-gate OFF · Velo ON (plunge 0.95, window 5, dots 1)",
"note": "RE-RUN confluence-build flipped non-edge to 1.43 key=both-dir-trend-rider+breaker-vol8-strict+iceberg5+buf0.2; low-win 24pct alt trend-rider; SOL gate did NOT transfer",
"degen": false
},
{
"sym": "ASML",
"warn": false,
"pf": 1.414,
"dd": 13.33,
"win": 52.28,
"n": 197,
"arch": "equity-robust-both",
"remicro": true,
"assetClass": "equity",
"sector": "Semis",
"family": "both-direction",
"status": "re-microtune",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts ON · Require Min R:R OFF · Cascade-Fade ONLY OFF",
"stops": "Stop-beyond-cascade OFF · Wall-TP OFF · Partial-TP ON",
"signals": "Iceberg ON (abs 3) · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate ON (maxLong 0.1, maxShort 0.39, veto 0.6) · Velo OFF",
"note": "JUICE2 robust base-engine CascFade-off+Iceberg3+SkipCascade+PartialTP+tight-LQX; veto crumb 0.7->0.6 cut DD 13.99->13.33 AND lifted PF 1.385->1.414 (S 1.215->1.248); veto0.5 worse 16.2DD; MaxLong0.12/MaxShort0.35 lifts PF 1.474 but DD15.5 lower S; 197tr deployable not 37tr mirage; both-dir",
"degen": false
},
{
"sym": "FIL",
"warn": false,
"pf": 1.403,
"dd": 28.12,
"win": 28.81,
"n": 59,
"arch": "crypto-trend-both-dir",
"remicro": false,
"assetClass": "crypto",
"sector": "Crypto",
"family": "both-direction",
"status": "ready",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts ON · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade OFF · Wall-TP ON (min-room 0.2) · Partial-TP OFF",
"signals": "Iceberg ON (abs 10) · BSL/SSL ON (pool 4, exh-vol 3, eliq OFF) · Breaker ON (vol 5)",
"gates": "LQX-gate ON (maxLong 0.1, maxShort 0.35, veto 0.7) · Velo OFF",
"note": "JUICE2 BINANCE:FILUSDT both-dir trend-rider; data shifted (more bars) N grew 40->59 at BrkVol5/exh3 deployable now 1.403/28.12DD/59tr TRUST 0.872->1.077; BrkVol6 sub-1 0.978; exh4 flat 1.368; velocity over-thins N28; MaxShort tighten kills profitable-shorts; DD structural 28pct downtrender",
"degen": false
},
{
"sym": "BCH",
"warn": true,
"pf": 1.375,
"dd": 10.18,
"win": 88.0,
"n": 50,
"arch": "crypto-fade-long",
"remicro": false,
"assetClass": "crypto",
"sector": "Crypto",
"family": "fade",
"status": "walk-forward",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 0.2, target-R 0.3) · Wall-TP OFF · Partial-TP ON",
"signals": "Iceberg OFF · BSL/SSL ON (pool 4, exh-vol 1.75, eliq OFF) · Breaker OFF",
"gates": "LQX-gate ON (maxLong 0.25, maxShort 1, veto 1) · Velo OFF",
"note": "BINANCE:BCHUSDT 4h; LONG-ONLY FADE archetype (clears PF1 unlike crash-alts); seed buf0.35 1.065/14.72DD/N50 -> buffer TIGHTEN 0.35->0.2 the lever (PF 1.065->1.375 DD 14.72->10.18) buf0.1 plateau; velocity ON thins N16; exh2.5 sub-1; 88pct win long-only = bull-regime walk-fwd MANDATORY; S=1.248",
"degen": false
},
{
"sym": "FET",
"warn": false,
"pf": 1.369,
"dd": 27.05,
"win": 32.65,
"n": 49,
"arch": "crypto-trend-both-dir",
"remicro": false,
"assetClass": "crypto",
"sector": "Crypto",
"family": "both-direction",
"status": "ready",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts ON · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade OFF · Wall-TP ON (min-room 0.2) · Partial-TP OFF",
"signals": "Iceberg ON (abs 10) · BSL/SSL ON (pool 4, exh-vol 3, eliq OFF) · Breaker ON (vol 4)",
"gates": "LQX-gate ON (maxLong 0.1, maxShort 0.2, veto 0.7) · Velo OFF",
"note": "JUICE2 BINANCE:FETUSDT both-dir trend-rider; KEY = BrkVol5->4 floods sample + MaxShort tighten 0.25->0.2 cut DD 36.67->27.05 keeping PF 1.369 N49; data shifted prior 37tr/1.454; BrkVol4/MS0.25 high-DD 36.67; BrkVol5/MS0.2 thin N36; exh non-binding; TRUST 0.697->0.880",
"degen": false
},
{
"sym": "VGT",
"warn": false,
"pf": 1.368,
"dd": 23.97,
"win": 35.71,
"n": 56,
"arch": "equity-confluence-long",
"remicro": true,
"assetClass": "equity",
"sector": "ETF",
"family": "fade",
"status": "re-microtune",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R ON · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 5, target-R 3) · Wall-TP ON (min-room 0.3) · Partial-TP ON",
"signals": "Iceberg ON (abs 7) · BSL/SSL ON (pool 2, exh-vol 2, eliq OFF) · Breaker ON (vol 4)",
"gates": "LQX-gate OFF · Velo ON (plunge 0.95, window 5, dots 1)",
"note": "RE-RUN confluence-build flipped non-edge to 1.37 key=long-only+buf5+breaker-vol4; breaker-vol2 floods 202tr@24pct win lift vol to 4 for quality; DD healthy 24pct tech ETF",
"degen": false
},
{
"sym": "QCOM",
"warn": false,
"pf": 1.31,
"dd": 26.28,
"win": 51.16,
"n": 43,
"arch": "semi-confluence-long-gated",
"remicro": true,
"assetClass": "equity",
"sector": "Semis",
"family": "fade",
"status": "re-microtune",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 3, target-R 1) · Wall-TP ON (min-room 0.3) · Partial-TP ON",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate ON (maxLong 0.4, maxShort def, veto 0.7) · Velo OFF",
"note": "JUICE2 BATS:QCOM fade-wall-gated long-only; base-engine bleeds knives (tight-LQX 0.74/N91 0.87/N66 all sub-1); proven fade-wall+CascStop-buf3+loose-LQX 0.4/0.7 = 1.31/26.28DD/43tr; velo over-thins N27; no-CascStop velo-off 1.08/N55 TRUST-tied but lower PF; buf8 worse 1.05/N27; prior 38tr/1.076 thin; TRUST 0.558->0.743 deployable; walk-fwd",
"degen": false
},
{
"sym": "MCHP",
"warn": false,
"pf": 1.282,
"dd": 39.22,
"win": 28.05,
"n": 82,
"arch": "semi-continuation-long-wall-gated",
"remicro": true,
"assetClass": "equity",
"sector": "Semis",
"family": "trend/continuation",
"status": "re-microtune",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY OFF",
"stops": "Stop-beyond-cascade OFF · Wall-TP ON (min-room 0.3) · Partial-TP OFF",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker ON (vol 3)",
"gates": "LQX-gate ON (maxLong 0.3, maxShort 0.39, veto 0.6) · Velo OFF",
"note": "JUICE2 BATS:MCHP continuation-wall; base-engine fades knives 0.91/N93 sub-1; continuation+Breaker3+Wall long-only 1.084/45.78DD/117tr -> tight-LQX 0.3/0.6 lifted PF to 1.282 AND cut DD to 39.22 N82 (gate helps NXPI-style); BrkVol5 lower 1.058/N90; DD structural 39pct volatile semi; prior 84tr/1.048; TRUST 0.764->0.921 deployable; walk-fwd high-DD",
"degen": false
},
{
"sym": "TLT",
"warn": false,
"pf": 1.272,
"dd": 17.66,
"win": 48.78,
"n": 205,
"arch": "fade-clean",
"remicro": true,
"assetClass": "equity",
"sector": "ETF",
"family": "fade",
"status": "re-microtune",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts ON · Require Min R:R ON · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 30, target-R 1) · Wall-TP ON (min-room 0.3) · Partial-TP ON",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate OFF · Velo OFF",
"note": "CLEAN cascade-fade; buffer sweep 30 (plateau 30-35) beats user-22 1.232->1.272 same DD; +18.05pct PnL; commit-fix made numeric sweeps real",
"degen": false
},
{
"sym": "VOO",
"warn": false,
"pf": 1.249,
"dd": 13.39,
"win": 43.1,
"n": 58,
"arch": "index-etf-robust-long",
"remicro": true,
"assetClass": "equity",
"sector": "ETF",
"family": "fade",
"status": "re-microtune",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY OFF",
"stops": "Stop-beyond-cascade OFF · Wall-TP OFF · Partial-TP OFF",
"signals": "Iceberg ON (abs 5) · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate ON (maxLong 0.5, maxShort 0.39, veto 0.85) · Velo OFF",
"note": "JUICE2 BATS:VOO S&P500-ETF robust base-engine; prior 30tr/1.849 fade-cascstop thin mirage; deployable = CascFade-OFF base + Iceberg-hits5 + SkipCascade + loose-LQX 0.5/0.85 long-only = 1.249/13.39DD/58tr; tight-LQX 0.3/0.6 1.214/11.18DD/N39 lower TRUST (N drop); IceHits3 floods N81 but PF1.012 collapses; IceHits5 best; 43pct win realistic; TRUST 0.825->1.065 deployable high-sample; walk-fwd",
"degen": false
},
{
"sym": "UK100GBP",
"warn": false,
"pf": 1.248,
"dd": 7.86,
"win": 33.33,
"n": 66,
"arch": "index-robust-long",
"remicro": true,
"assetClass": "equity",
"sector": "Index",
"family": "fade",
"status": "re-microtune",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 3, target-R 3) · Wall-TP OFF · Partial-TP OFF",
"signals": "Iceberg ON (abs 3) · BSL/SSL ON (pool 2, exh-vol 1, eliq OFF) · Breaker OFF",
"gates": "LQX-gate OFF · Velo OFF",
"note": "JUICE2 OANDA:UK100GBP FTSE robust; prior 38tr/1.537 needed velocity; deployable now = cascade-fade + Iceberg3 + BSL2/1 + tight buf3 long-only = 1.248/7.86DD/66tr (velocity OFF - over-filtered to N22); ice7+BSL+velo buf5 1.353/N22 thin / no-velo 1.843/N26 thin; lowering ice3+buf3 floods clean N66; very low DD 7.9pct; TRUST 0.907->1.157 deployable higher-sample",
"degen": false
},
{
"sym": "ADA",
"warn": false,
"pf": 1.241,
"dd": 19.07,
"win": 28.36,
"n": 67,
"arch": "crypto-trend-both-dir",
"remicro": false,
"assetClass": "crypto",
"sector": "Crypto",
"family": "both-direction",
"status": "ready",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts ON · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade OFF · Wall-TP ON (min-room 0.2) · Partial-TP OFF",
"signals": "Iceberg ON (abs 10) · BSL/SSL ON (pool 4, exh-vol 1, eliq OFF) · Breaker ON (vol 6)",
"gates": "LQX-gate ON (maxLong 0.1, maxShort 0.35, veto 0.7) · Velo OFF",
"note": "JUICE2 BINANCE:ADAUSDT both-dir trend-rider; data shifted since prior run (more downtrend bars) prior 40tr/1.686 no longer reproduces; deployable now = BrkVol6 1.241/19.07DD/67tr clears N60 floor TRUST 0.991->1.043; BrkVol8 1.233/64 similar; MaxShort0.25 collapses shorts PF0.75 (shorts=profit source); exh2 flat; high-sample beats thin mirage",
"degen": false
},
{
"sym": "ORCL",
"warn": true,
"pf": 1.23,
"dd": 26.01,
"win": 50.0,
"n": 80,
"arch": "fade-long-wall",
"remicro": true,
"assetClass": "equity",
"sector": "Single-name",
"family": "fade",
"status": "re-microtune",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R ON · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 1, target-R 1) · Wall-TP ON (min-room 0.3) · Partial-TP ON",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate OFF · Velo OFF",
"note": "long-only fade-wall; tighter buffer cuts DD (buf5 36 -> buf1 26); velo HURT (DD up); marginal software 1.23/26; clears PF1 + N80",
"degen": false
},
{
"sym": "EURJPY",
"warn": false,
"pf": 1.187,
"dd": 11.22,
"win": 26.42,
"n": 53,
"arch": "forex-fade-both-cascstop",
"remicro": false,
"assetClass": "forex",
"sector": "Forex",
"family": "both-direction",
"status": "ready",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts ON · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 16, target-R 3) · Wall-TP ON (min-room 0.2) · Partial-TP OFF",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate OFF · Velo OFF",
"note": "OANDA:EURJPY 4h BOTH-DIR cascade-fade; JPY-cross marginal high-DD; needs MID buffer (buf30 0.771/N13<floor buf18 1.135/N47 buf16 1.187/DD11.22/N53 buf14 1.007/N64); buf16 local optimum highest PF lowest DD; long-only thins N10; iceberg HURT (1.086/DD13); structural DD~11pct eats S; 26.42pct win symmetric; S=1.067 marginal clears PF1+floor",
"degen": false
},
{
"sym": "TXN",
"warn": false,
"pf": 1.169,
"dd": 19.12,
"win": 46.67,
"n": 75,
"arch": "semi-robust-long",
"remicro": true,
"assetClass": "equity",
"sector": "Semis",
"family": "fade",
"status": "re-microtune",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY OFF",
"stops": "Stop-beyond-cascade OFF · Wall-TP OFF · Partial-TP OFF",
"signals": "Iceberg ON (abs 3) · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate ON (maxLong 0.3, maxShort 0.39, veto 0.6) · Velo OFF",
"note": "JUICE2 BATS:TXN robust base-engine BIG sample; low-vol analog semi takes base-engine well (unlike NXPI/QCOM knife-catchers); CascFade-OFF + Iceberg3 + SkipCascade + tight-LQX 0.3/0.6 long-only = 1.169/19.12DD/75tr; tighter 0.25/0.5 1.174/N56 fewer; loose 0.5/0.85 1.177/N121 but DD25.6 higher; 0.3/0.6 lowest-DD best S; prior 34tr/1.455 thin; TRUST 0.645->0.981 deployable low-DD; 47pct win",
"degen": false
},
{
"sym": "TIA",
"warn": false,
"pf": 1.16,
"dd": 39.4,
"win": 19.47,
"n": 113,
"arch": "crypto-trend-both-dir",
"remicro": false,
"assetClass": "crypto",
"sector": "Crypto",
"family": "both-direction",
"status": "ready",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts ON · Require Min R:R OFF · Cascade-Fade ONLY OFF",
"stops": "Stop-beyond-cascade OFF · Wall-TP ON (min-room 0.2) · Partial-TP OFF",
"signals": "Iceberg ON (abs 10) · BSL/SSL ON (pool 4, exh-vol 1, eliq OFF) · Breaker ON (vol 10)",
"gates": "LQX-gate ON (maxLong 0.1, maxShort 0.25, veto 0.7) · Velo OFF",
"note": "BINANCE:TIAUSDT 4h severe downtrender (2023-launch near top); long-only fade catastrophic 0.05/DD70; BOTH-DIR trend-rider clears PF1 marginally; KEY = MaxShort TIGHTEN 0.5->0.25 (PF 1.0->1.16 DD 45->39.4); BrkVol10 plateau (12 identical); exh2 no help; DD structurally ~39pct high-quality like DOT/INTC; 19pct win symmetric; S=0.832 marginal high-DD walk-fwd recommended",
"degen": false
},
{
"sym": "ADI",
"warn": false,
"pf": 1.149,
"dd": 20.89,
"win": 47.76,
"n": 67,
"arch": "semi-robust-long-gated",
"remicro": true,
"assetClass": "equity",
"sector": "Semis",
"family": "fade",
"status": "re-microtune",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY OFF",
"stops": "Stop-beyond-cascade OFF · Wall-TP OFF · Partial-TP OFF",
"signals": "Iceberg ON (abs 3) · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate ON (maxLong 0.25, maxShort 0.39, veto 0.5) · Velo OFF",
"note": "JUICE2 BATS:ADI robust base-engine; low-vol analog semi (TXN sibling) takes base-engine well; CascFade-OFF + Iceberg3 + SkipCascade + tight-LQX 0.25/0.5 long-only = 1.149/20.89DD/67tr; loose 0.3/0.6 DD31.93 higher; tighter 0.2/0.5 PF1.038/N54 lower; 0.25/0.5 best balance gate cuts DD 32->21; prior 31tr/1.836 thin; TRUST 0.842->0.950 deployable low-DD; 48pct win",
"degen": false
},
{
"sym": "XAUUSD",
"warn": false,
"pf": 1.129,
"dd": 6.8,
"win": 38.33,
"n": 60,
"arch": "comdty-robust-long-gated",
"remicro": true,
"assetClass": "equity",
"sector": "Commodity",
"family": "fade",
"status": "re-microtune",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY OFF",
"stops": "Stop-beyond-cascade OFF · Wall-TP OFF · Partial-TP OFF",
"signals": "Iceberg ON (abs 3) · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate ON (maxLong 0.3, maxShort 0.39, veto 0.6) · Velo OFF",
"note": "JUICE2 OANDA:XAUUSD gold robust base-engine VERY LOW DD; CascFade-OFF base + Iceberg3 + SkipCascade + tight-LQX 0.3/0.6 long-only = 1.129/6.80DD/60tr exactly clears N60; IceHits5 1.222/6.18DD/N49 higher PF but lower TRUST (N drop); loose-LQX 0.5/0.85 0.966/14.14DD/N101 sub-1 knives; tight gate + IceHits3 best TRUST 1.057; 38pct win; clean gold uptrend low-DD; new symbol TRUST n/a->1.057 deployable; walk-fwd",
"degen": false
},
{
"sym": "AVGO",
"warn": false,
"pf": 1.126,
"dd": 24.66,
"win": 47.83,
"n": 69,
"arch": "semi-robust-long-gated",
"remicro": true,
"assetClass": "equity",
"sector": "Semis",
"family": "fade",
"status": "re-microtune",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY OFF",
"stops": "Stop-beyond-cascade OFF · Wall-TP OFF · Partial-TP OFF",
"signals": "Iceberg ON (abs 3) · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate ON (maxLong 0.3, maxShort 0.39, veto 0.6) · Velo OFF",
"note": "JUICE2 BATS:AVGO robust base-engine; DATA SHIFT raised DD vs prior clean-fade 8.84; CascFade-OFF + Iceberg3 + SkipCascade + tight-LQX 0.3/0.6 long-only = 1.126/24.66DD/69tr; loose 0.5/0.85 DD29.7; clean-fade PF1.306 but only N44 lower TRUST; tight-gate cuts DD+lifts PF; prior 35tr/1.315; TRUST 0.704->0.903 deployable high-sample; 48pct win walk-fwd",
"degen": false
},
{
"sym": "SPX500USD",
"warn": false,
"pf": 1.081,
"dd": 13.57,
"win": 46.99,
"n": 83,
"arch": "index-robust-long",
"remicro": true,
"assetClass": "equity",
"sector": "Index",
"family": "fade",
"status": "re-microtune",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY OFF",
"stops": "Stop-beyond-cascade OFF · Wall-TP OFF · Partial-TP OFF",
"signals": "Iceberg ON (abs 3) · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate ON (maxLong 0.5, maxShort 0.39, veto 0.85) · Velo OFF",
"note": "JUICE2 OANDA:SPX500USD robust base-engine; prior 34tr/1.468 fade thinned (now buf5+ice7+BSL N13 mirage); deployable = CascFade-OFF base + Iceberg3 + loose-LQX 0.5/0.85 long-only = 1.081/13.57DD/83tr; SkipCascade OFF crumb (on=1.041/N75); tight-LQX failed PF0.601; 47pct win realistic low-DD; TRUST 0.747->0.952 deployable higher-sample",
"degen": false
},
{
"sym": "US30USD",
"warn": false,
"pf": 1.056,
"dd": 9.29,
"win": 44.72,
"n": 123,
"arch": "index-robust-long",
"remicro": true,
"assetClass": "equity",
"sector": "Index",
"family": "fade",
"status": "re-microtune",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY OFF",
"stops": "Stop-beyond-cascade OFF · Wall-TP OFF · Partial-TP OFF",
"signals": "Iceberg ON (abs 3) · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate ON (maxLong 0.5, maxShort 0.39, veto 0.85) · Velo OFF",
"note": "JUICE2 OANDA:US30USD Dow robust base-engine; prior 44tr/1.291 fade; deployable = CascFade-OFF base + Iceberg3 + loose-LQX 0.5/0.85 + SkipCascade long-only = 1.056/9.29DD/123tr; SkipCascade ON crumb (off=1.014/N127); very low DD 9.3pct big sample; 45pct win realistic; TRUST 0.859->0.966 deployable robust low-DD",
"degen": false
},
{
"sym": "AMAT",
"warn": false,
"pf": 1.053,
"dd": 45.37,
"win": 42.48,
"n": 113,
"arch": "semi-robust-marginal",
"remicro": true,
"assetClass": "equity",
"sector": "Semis",
"family": "fade",
"status": "re-microtune",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY OFF",
"stops": "Stop-beyond-cascade OFF · Wall-TP OFF · Partial-TP OFF",
"signals": "Iceberg ON (abs 3) · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate ON (maxLong 0.5, maxShort 0.39, veto 0.85) · Velo OFF",
"note": "JUICE2 BATS:AMAT prior verdict was genuine-nonedge but base-engine robust path clears PF1 marginally now; CascFade-OFF + Iceberg3 + SkipCascade + loose-LQX 0.5/0.85 long-only = 1.053/45.37DD/113tr; breaker floods 240tr/0.92/77DD (continuation bleeds); tight-LQX 0.3/0.6 sub-1 0.874/N76; MaxLong0.4/veto0.7 cuts DD to 40 but PF0.973; DD structural 40-47pct volatile semi; barely an edge TRUST 0->0.724 high-sample but high-DD; walk-fwd",
"degen": false
},
{
"sym": "XLY",
"warn": false,
"pf": 1.044,
"dd": 16.13,
"win": 38.1,
"n": 84,
"arch": "index-etf-robust-long-gated",
"remicro": true,
"assetClass": "equity",
"sector": "ETF",
"family": "fade",
"status": "re-microtune",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY OFF",
"stops": "Stop-beyond-cascade OFF · Wall-TP OFF · Partial-TP OFF",
"signals": "Iceberg ON (abs 3) · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate ON (maxLong 0.4, maxShort 0.39, veto 0.7) · Velo OFF",
"note": "JUICE2 BATS:XLY discretionary-ETF base-engine marginal; CascFade-OFF + Iceberg3 + SkipCascade + LQX 0.4/0.7 long-only = 1.044/16.13DD/84tr clears N60; tighter 0.3/0.6 1.007/N67; IceHits5 crashes 0.645 (opposite of staples); fade+CascStop buf3 2.047/31DD/N31 higher PF but TRUST 0.806 (high-DD thin); base-engine wins TRUST low-DD; prior 34tr/1.798 fade-cascstop; 38pct win; TRUST 1.47->0.899 deployable high-sample marginal; walk-fwd",
"degen": false
},
{
"sym": "TRX",
"warn": false,
"pf": 1.032,
"dd": 7.21,
"win": 32.14,
"n": 28,
"arch": "crypto-nfloor-defer",
"remicro": false,
"assetClass": "crypto",
"sector": "Crypto",
"family": "fade",
"status": "ready",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 0.2, target-R 0.3) · Wall-TP ON (min-room 0.2) · Partial-TP ON",
"signals": "Iceberg OFF · BSL/SSL ON (pool 4, exh-vol 1.75, eliq OFF) · Breaker OFF",
"gates": "LQX-gate ON (maxLong 0.25, maxShort 1, veto 1) · Velo OFF",
"note": "N-FLOOR BLOCKED defer 4h BINANCE:TRXUSDT; steady Tron uptrender VERY low DD 7.21pct; long-only fade gated buf0.2 PF1.032/N28 buf0.35 PF1.013/N28 both sub-floor; only ~28 quality trades structural; loosening gates (LQX-off 0.223/N64 ML0.4 0.821/N48 iceberg5 0.789/N52) ALL bring losers PF<1; profitable but too thin like VGT/AMAT; defer",
"degen": false
},
{
"sym": "EURGBP",
"warn": true,
"pf": 1.027,
"dd": 5.33,
"win": 58.82,
"n": 34,
"arch": "forex-fade-long-marginal",
"remicro": false,
"assetClass": "forex",
"sector": "Forex",
"family": "fade",
"status": "walk-forward",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 5, target-R 3) · Wall-TP ON (min-room 0.2) · Partial-TP OFF",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate OFF · Velo OFF",
"note": "OANDA:EURGBP 4h tight-range cross; LONG-ONLY is the edge (both-dir buf23 PF24/N19 long-only buf18 1.412/N15 all N-floor-blocked at high PF); buffer the lever low-vol cross wants TIGHT (opposite of majors); buf10 1.623/N24 buf7 1.114/N29 buf5 1.027/N34 (only N>=30 point - trades 30-34 are losers dragging PF); short-only bleeds 0.403; MARGINAL barely clears PF1 at floor; 58.82pct win long-only walk-fwd MANDATORY; S=0.975",
"degen": false
},
{
"sym": "SEI",
"warn": false,
"pf": 1.003,
"dd": 47.37,
"win": 15.67,
"n": 319,
"arch": "crypto-nonedge",
"remicro": false,
"assetClass": "crypto",
"sector": "Crypto",
"family": "fade",
"status": "ready",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts ON · Require Min R:R OFF · Cascade-Fade ONLY OFF",
"stops": "Stop-beyond-cascade OFF · Wall-TP ON (min-room 0.2) · Partial-TP OFF",
"signals": "Iceberg ON (abs 10) · BSL/SSL ON (pool 4, exh-vol 1, eliq OFF) · Breaker ON (vol 4)",
"gates": "LQX-gate ON (maxLong 0.1, maxShort 0.35, veto 0.7) · Velo OFF",
"note": "NON-EDGE 4h BINANCE:SEIUSDT recent-launch bleeder (APT/SUI family); long-only fade catastrophic 0.45/DD50/N52 (catches knives); both-dir trend-rider tops at PF1.003 only with DD47pct (breaker floods 319tr); cleaner-DD configs all sub-1 (BrkVol8/MaxShort0.25 0.959/DD30.7 MaxShort0.2 0.99/DD39); never clears PF1 AND reasonable DD; defer like APT/SUI/ICP",
"degen": false
},
{
"sym": "LDO",
"warn": false,
"pf": 0.909,
"dd": 51.24,
"win": 13.92,
"n": 273,
"arch": "crypto-nonedge",
"remicro": false,
"assetClass": "crypto",
"sector": "Crypto",
"family": "fade",
"status": "ready",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts ON · Require Min R:R OFF · Cascade-Fade ONLY OFF",
"stops": "Stop-beyond-cascade OFF · Wall-TP ON (min-room 0.2) · Partial-TP OFF",
"signals": "Iceberg ON (abs 10) · BSL/SSL ON (pool 4, exh-vol 1, eliq OFF) · Breaker ON (vol 10)",
"gates": "LQX-gate ON (maxLong 0.1, maxShort 0.5, veto 0.7) · Velo OFF",
"note": "NON-EDGE 4h BINANCE:LDOUSDT 2021-launch DeFi deep 2022 drawdown bleeds both directions; long-only fade 0.531/DD54; both-dir trend-rider tops PF0.909/DD51 (BrkVol10/MaxShort0.5 best); MaxShort tighten 0.25 KILLS profitable-shorts 0.379; never clears PF1; defer like AAVE/LINK DeFi misfit",
"degen": false
},
{
"sym": "SUI",
"warn": false,
"pf": 0.881,
"dd": 32.83,
"win": 15.35,
"n": 254,
"arch": "crypto-confluence-nonedge",
"remicro": false,
"assetClass": "crypto",
"sector": "Crypto",
"family": "fade",
"status": "ready",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts ON · Require Min R:R ON · Cascade-Fade ONLY OFF",
"stops": "Stop-beyond-cascade OFF · Wall-TP ON (min-room 0.2) · Partial-TP OFF",
"signals": "Iceberg ON (abs 10) · BSL/SSL ON (pool 4, exh-vol 1, eliq OFF) · Breaker ON (vol 12)",
"gates": "LQX-gate ON (maxLong 0.1, maxShort 0.35, veto 0.7) · Velo OFF",
"note": "RE-RUN full confluence stack still sub-1 best 0.881 both-dir trend-rider breaker12 tight-LQX; bare fade bled DD75; tight-LQX cut DD75->33; breaker sweep plateaus ~0.88; MaxShort0.2 kills shorts PF0.76; recent-2023 launch bleeds both directions; genuine non-edge",
"degen": false
},
{
"sym": "ATOM",
"warn": false,
"pf": 0.853,
"dd": 49.03,
"win": 22.31,
"n": 130,
"arch": "crypto-confluence-nonedge",
"remicro": false,
"assetClass": "crypto",
"sector": "Crypto",
"family": "fade",
"status": "ready",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts ON · Require Min R:R ON · Cascade-Fade ONLY OFF",
"stops": "Stop-beyond-cascade ON (buffer 0.2, target-R 4) · Wall-TP ON (min-room 0.3) · Partial-TP ON",
"signals": "Iceberg ON (abs 5) · BSL/SSL ON (pool 2, exh-vol 2, eliq OFF) · Breaker ON (vol 4)",
"gates": "LQX-gate OFF · Velo ON (plunge 0.95, window 5, dots 1)",
"note": "RE-RUN full confluence stack still sub-1 (best 0.853 continuation-both); fade-only 0.38 fades dont reverse (16pct win); tight-gate cuts DD but PF 0.73; genuine non-edge",
"degen": false
},
{
"sym": "RUNE",
"warn": false,
"pf": 0.85,
"dd": 29.57,
"win": 21.74,
"n": 69,
"arch": "crypto-nonedge",
"remicro": false,
"assetClass": "crypto",
"sector": "Crypto",
"family": "fade",
"status": "ready",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts ON · Require Min R:R OFF · Cascade-Fade ONLY OFF",
"stops": "Stop-beyond-cascade OFF · Wall-TP ON (min-room 0.2) · Partial-TP OFF",
"signals": "Iceberg ON (abs 10) · BSL/SSL ON (pool 4, exh-vol 1, eliq OFF) · Breaker ON (vol 4)",
"gates": "LQX-gate ON (maxLong 0.1, maxShort 0.35, veto 0.7) · Velo OFF",
"note": "NON-EDGE 4h BINANCE:RUNEUSDT severe downtrender (THORChain 2021 collapse); long-only fade catastrophic 0.054/DD66; both-dir trend-rider tops PF0.85 (BrkVol4 best BrkVol6 0.744 BrkVol8 0.619); MaxShort/exh levers no help; never clears PF1; defer like LINK/ATOM/OP downtrender family",
"degen": false
},
{
"sym": "WIF",
"warn": false,
"pf": 0.842,
"dd": 55.9,
"win": 29.63,
"n": 54,
"arch": "crypto-nonedge",
"remicro": false,
"assetClass": "crypto",
"sector": "Crypto",
"family": "fade",
"status": "ready",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 0.35, target-R 0.3) · Wall-TP ON (min-room 0.2) · Partial-TP ON",
"signals": "Iceberg OFF · BSL/SSL ON (pool 4, exh-vol 1.75, eliq OFF) · Breaker OFF",
"gates": "LQX-gate ON (maxLong 0.25, maxShort 1, veto 1) · Velo OFF",
"note": "NON-EDGE 4h BINANCE:WIFUSDT extreme memecoin volatility bleeds both directions; long-only fade 0.84/DD56/N54 (catches knives); both-dir trend-rider WORSE 0.66/DD70/N237; tight-gate/BrkVol kills the crash-shorts 0.21; buf0.1 fade no better 0.84; no archetype clears PF1; defer like SEI/LINK extreme-vol misfit",
"degen": false
},
{
"sym": "OP",
"warn": false,
"pf": 0.795,
"dd": 29.79,
"win": 9.76,
"n": 82,
"arch": "crypto-nonedge",
"remicro": false,
"assetClass": "crypto",
"sector": "Crypto",
"family": "fade",
"status": "ready",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts ON · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade OFF · Wall-TP ON (min-room 0.2) · Partial-TP OFF",
"signals": "Iceberg ON (abs 10) · BSL/SSL ON (pool 4, exh-vol 3, eliq OFF) · Breaker ON (vol 8)",
"gates": "LQX-gate ON (maxLong 0.1, maxShort 0.5, veto 0.7) · Velo OFF",
"note": "NON-EDGE 4h BINANCE:OPUSDT; severe downtrender bleeds both directions; long-only fade 0.354/40.63DD/N50 terrible; both-dir trend-rider BrkVol8 0.728/35.26DD MaxShort0.5 0.795/29.79DD/N82 best BrkVol12 0.767/32.28DD; no config clears PF1; defer like LINK/LTC/ATOM; 2022-launch L2 chronic decline",
"degen": false
},
{
"sym": "APT",
"warn": false,
"pf": 0.794,
"dd": 31.38,
"win": 16.91,
"n": 136,
"arch": "crypto-confluence-nonedge",
"remicro": false,
"assetClass": "crypto",
"sector": "Crypto",
"family": "fade",
"status": "ready",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts ON · Require Min R:R ON · Cascade-Fade ONLY OFF",
"stops": "Stop-beyond-cascade OFF · Wall-TP ON (min-room 0.2) · Partial-TP OFF",
"signals": "Iceberg ON (abs 10) · BSL/SSL ON (pool 4, exh-vol 1, eliq OFF) · Breaker ON (vol 8)",
"gates": "LQX-gate ON (maxLong 0.1, maxShort 0.25, veto 0.7) · Velo OFF",
"note": "RE-RUN full confluence stack still sub-1 best 0.794 both-dir MaxShort0.25 breaker8; fade-long bled DD51 breaker6 worse 0.54; trend-rider floods 323tr DD63; recent-launch alt bleeds both directions; genuine non-edge",
"degen": false
},
{
"sym": "LINK",
"warn": false,
"pf": 0.687,
"dd": 56.15,
"win": 17.97,
"n": 128,
"arch": "crypto-confluence-nonedge",
"remicro": false,
"assetClass": "crypto",
"sector": "Crypto",
"family": "fade",
"status": "ready",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R ON · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 0.35, target-R 4) · Wall-TP ON (min-room 0.3) · Partial-TP ON",
"signals": "Iceberg ON (abs 7) · BSL/SSL ON (pool 2, exh-vol 2, eliq OFF) · Breaker ON (vol 4)",
"gates": "LQX-gate OFF · Velo ON (plunge 0.95, window 5, dots 1)",
"note": "RE-RUN full confluence stack still sub-1 (best 0.687); win stuck ~18pct across both-dir/long-only/continuation/buf0.35-2/tight-gate; fade reversals dont fire clean on LINK 4h; genuine non-edge",
"degen": false
},
{
"sym": "ONDO",
"warn": false,
"pf": 0.586,
"dd": 25.71,
"win": 30.77,
"n": 26,
"arch": "crypto-nonedge",
"remicro": false,
"assetClass": "crypto",
"sector": "Crypto",
"family": "fade",
"status": "ready",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 0.35, target-R 0.3) · Wall-TP ON (min-room 0.2) · Partial-TP ON",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate ON (maxLong 0.25, maxShort 1, veto 1) · Velo OFF",
"note": "NON-EDGE 4h BINANCE:ONDOUSDT 2024-launch RWA token bleeds both directions; long-only fade 0.586/DD25.7/N26 best PF; both-dir trend-rider WORSE (BrkVol6 0.525/DD43 BrkVol8/MaxShort0.25 0.439 kills profitable-shorts MaxShort0.5 0.568); no archetype clears PF1; defer like SEI/ONDO recent-launch family",
"degen": false
},
{
"sym": "USDCHF",
"warn": true,
"pf": 78.399,
"dd": 2.22,
"win": 21.15,
"n": 52,
"arch": "forex-fade-short-cascstop",
"remicro": false,
"assetClass": "forex",
"sector": "Forex",
"family": "fade",
"status": "walk-forward",
"date": "21 Jun 2026",
"dateRaw": "2026-06-21T12:00",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 16, target-R 3) · Wall-TP ON (min-room 0.2) · Partial-TP OFF",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate OFF · Velo OFF",
"note": "OANDA:USDCHF 4h SHORT-ONLY cascade-fade (structural CHF strength = shorting USDCHF bounces is the edge); both-dir fade bleeds (buf23 0.909/N48) long side is the bleed; SHORT-ONLY huge edge (buf12 1.905/N101 buf16 78.4/N52 buf18 67/N41 buf23 48/N23<floor); buf16 best N>=30 high-PF; EXTREME PF outlier-driven (few monster CHF-rally shorts tiny DD 2.22) FRAGILE; robust alt buf12 PF1.9/N101 or partial-ON 72/DD1.65/N57; short-only structural walk-fwd MANDATORY; S=76.7",
"degen": true
}
];
window.DEEP_STATS = {"count": 107, "universe": 50, "equityCount": 60, "cryptoCount": 36, "forexCount": 11, "edges": 97, "bothDirEdges": 24, "degenCount": 1, "ready": 52, "walkfwd": 36, "remicro": 19, "above15": 66, "topPF": 9.149, "topSym": "XCUUSD", "cleanestDD": 2.28, "cleanestSym": "EURUSD", "cryptoMeanDD": 24.2, "equityMeanDD": 20.3, "date": "21 Jun 2026", "dateRaw": "2026-06-21T12:00", "byClass": {"equity": {"n": 60, "meanPF": 2.2, "meanDD": 20.3, "topPF": 9.149, "topSym": "XCUUSD", "cleanestDD": 4.65, "cleanestSym": "SCHD", "edges": 60}, "crypto": {"n": 36, "meanPF": 1.51, "meanDD": 24.2, "topPF": 4.759, "topSym": "DOGE", "cleanestDD": 4.29, "cleanestSym": "DOGE", "edges": 26}, "forex": {"n": 11, "meanPF": 3.47, "meanDD": 6.2, "topPF": 8.057, "topSym": "EURUSD", "cleanestDD": 2.22, "cleanestSym": "USDCHF", "edges": 11}}, "sect": {"ETF": {"n": 19, "meanPF": 2.1, "best": 4.533, "bestSym": "GLD", "edges": 19, "ready": 13}, "Semis": {"n": 20, "meanPF": 1.71, "best": 3.837, "bestSym": "LRCX", "edges": 20, "ready": 12}, "Single-name": {"n": 11, "meanPF": 2.91, "best": 5.748, "bestSym": "DE", "edges": 11, "ready": 10}, "Commodity": {"n": 5, "meanPF": 3.8, "best": 9.149, "bestSym": "XCUUSD", "edges": 5, "ready": 4}, "Index": {"n": 5, "meanPF": 1.33, "best": 1.741, "bestSym": "DE30EUR", "edges": 5, "ready": 2}, "Crypto": {"n": 36, "meanPF": 1.51, "best": 4.759, "bestSym": "DOGE", "edges": 26, "ready": 36}, "Forex": {"n": 11, "meanPF": 3.47, "best": 8.057, "bestSym": "EURUSD", "edges": 11, "ready": 11}}};
window.DEEP_FOREX = {"sym": "EURUSD", "pf": 1.4, "dd": 16.74, "net": 72.65, "note": "the namesake forex baseline (user-reported) trailed buy-and-hold; the tuned both-direction FX cells (GBPUSD 3.41, USDJPY 3.03) far exceed it."};
