/* LIQUIDEX FRAMEWORK — deep-tuned book (36/52 symbols, per-symbol best config). Auto-generated from BEST_PARAMS_PER_SYMBOL.md. */
window.DEEP_BOOK = [
{
"sym": "DE",
"warn": true,
"pf": 5.748,
"dd": 23.62,
"win": 86.84,
"n": 76,
"arch": "fade-long",
"remicro": false,
"sector": "Single-name",
"family": "fade",
"status": "walk-forward",
"date": "3:33 pm · 20 Jun 2026",
"dateRaw": "2026-06-20T15:33",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R ON · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 18, target-R 1) · Wall-TP ON (min-room 0.3) · Partial-TP ON",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate OFF · Velo OFF",
"note": "long-only clean-fade buf18; 1.37->5.75 BUT 87pct win = BULL-REGIME ARTIFACT (DE only uptrended 20-26); buy-dip works in-sample only; expect heavy OOS decay; WALK-FWD MANDATORY before any trust"
},
{
"sym": "GLD",
"warn": true,
"pf": 4.533,
"dd": 18.83,
"win": 82.81,
"n": 64,
"arch": "fade-long-ice",
"remicro": false,
"sector": "ETF",
"family": "fade",
"status": "walk-forward",
"date": "3:33 pm · 20 Jun 2026",
"dateRaw": "2026-06-20T15:33",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R ON · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 22, target-R 1) · Wall-TP ON (min-room 0.3) · Partial-TP ON",
"signals": "Iceberg ON (abs 3) · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate OFF · Velo OFF",
"note": "long-only + ICEBERG(3) + buf22; iceberg=the GLD key (S1 hinted); 2.46->4.53; buf8=0.70 (needs wide); ice5 over-filters; 83pct win long-only = bull-regime walk-fwd mandatory"
},
{
"sym": "V",
"warn": true,
"pf": 4.443,
"dd": 25.45,
"win": 81.25,
"n": 80,
"arch": "fade-long",
"remicro": false,
"sector": "Single-name",
"family": "fade",
"status": "walk-forward",
"date": "3:33 pm · 20 Jun 2026",
"dateRaw": "2026-06-20T15:33",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R ON · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 18, target-R 1) · Wall-TP ON (min-room 0.3) · Partial-TP ON",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate OFF · Velo OFF",
"note": "long-only clean-fade buf18 (plateau 18-25); shorts off (Visa uptrend); 1.36->4.44; +120pct PnL; 81pct win on 80tr; HIGH-PF walk-fwd critical"
},
{
"sym": "COST",
"warn": true,
"pf": 3.851,
"dd": 22.96,
"win": 78.13,
"n": 64,
"arch": "fade-long",
"remicro": false,
"sector": "Single-name",
"family": "fade",
"status": "walk-forward",
"date": "3:33 pm · 20 Jun 2026",
"dateRaw": "2026-06-20T15:33",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R ON · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 18, target-R 1) · Wall-TP ON (min-room 0.3) · Partial-TP ON",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate OFF · Velo OFF",
"note": "SHORTS OFF was the lever (secular uptrend; shorting rips bled to 0.75); long-only clean-fade buf18 (plateau 18-25); 1.39->3.85; +65pct; 78pct win; HIGH-PF on 64tr = walk-fwd critical"
},
{
"sym": "LRCX",
"warn": true,
"pf": 3.837,
"dd": 26.87,
"win": 83.33,
"n": 30,
"arch": "fade-long-cascstop",
"remicro": false,
"sector": "Semis",
"family": "fade",
"status": "walk-forward",
"date": "3:33 pm · 20 Jun 2026",
"dateRaw": "2026-06-20T15:33",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 5, target-R 1) · Wall-TP ON (min-room 0.3) · Partial-TP OFF",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate ON (maxLong 0.5, maxShort 0.5, veto 0.85) · Velo OFF",
"note": "CascStop binds buffer; sweep buf5 = sharp peak (3.84/30) buf3 1.57/DD33 buf8 3.69/N26<floor; tight gates cut N to 18 no DD help; 83pct win + DD27pct = bull-regime artifact; walk-fwd mandatory"
},
{
"sym": "XLV",
"warn": true,
"pf": 3.798,
"dd": 10.52,
"win": 86.96,
"n": 46,
"arch": "gated-continuation-fade",
"remicro": false,
"sector": "ETF",
"family": "continuation",
"status": "walk-forward",
"date": "3:33 pm · 20 Jun 2026",
"dateRaw": "2026-06-20T15:33",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R ON · Cascade-Fade ONLY OFF",
"stops": "Stop-beyond-cascade OFF · Wall-TP ON (min-room 0.3) · Partial-TP OFF",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate ON (maxLong def, maxShort def, veto def) · Velo ON (plunge def, window def, dots def)",
"note": "buffer sweep 8 (plateau 8-11) on gated-continuation seed; clean-fade collapsed to N=10; buf18 N=16 too wide; seed-default 1.95/80 -> buf8 3.80/46; gates ON drive trade volume here (opposite of KO/TLT); 87pct win long-only = bull-regime walk-fwd mandatory"
},
{
"sym": "XLK",
"warn": true,
"pf": 3.184,
"dd": 11.73,
"win": 46.15,
"n": 39,
"arch": "fade-long-ice",
"remicro": false,
"sector": "ETF",
"family": "fade",
"status": "walk-forward",
"date": "3:33 pm · 20 Jun 2026",
"dateRaw": "2026-06-20T15:33",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade OFF · Wall-TP ON (min-room 0.3) · Partial-TP OFF",
"signals": "Iceberg ON (abs 6) · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate ON (maxLong def, maxShort def, veto def) · Velo OFF",
"note": "fade seed buffer NON-BINDING (CascStop off); CascStop+buf18 bloated DD to 31pct N=11; real lever = Min iceberg absorption sweep 6 (plateau climbs 5->7 but N=31 cliff at 7); 2.39/69 seed -> abs6 3.18/39; long-only tech-ETF uptrend = walk-fwd mandatory"
},
{
"sym": "MA",
"warn": true,
"pf": 2.383,
"dd": 8.87,
"win": 36.36,
"n": 33,
"arch": "fade-long-wall-gated",
"remicro": false,
"sector": "Single-name",
"family": "fade",
"status": "walk-forward",
"date": "3:33 pm · 20 Jun 2026",
"dateRaw": "2026-06-20T15:33",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade OFF · Wall-TP ON (min-room 0.3) · Partial-TP OFF",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate ON (maxLong 0.4, maxShort 0.5, veto 0.85) · Velo OFF",
"note": "V-sibling but clean cascade-fade too thin (buf8 N19/buf18 N5); wall-fade IS trade path; LQX gate helps here (unlike clean faders); MaxLong tighten 0.5->0.4 lifts 2.25->2.38 (0.3 over-tightens N27 DD15); long-only MA uptrend = walk-fwd mandatory"
},
{
"sym": "QQQ",
"warn": true,
"pf": 2.317,
"dd": 8.69,
"win": 46.88,
"n": 32,
"arch": "fade-long-wall",
"remicro": false,
"sector": "ETF",
"family": "fade",
"status": "walk-forward",
"date": "3:33 pm · 20 Jun 2026",
"dateRaw": "2026-06-20T15:33",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade OFF · Wall-TP ON (min-room 0.5) · Partial-TP OFF",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate OFF · Velo ON (plunge def, window def, dots def)",
"note": "clean wall-fade buffer NON-BINDING (CascStop off); iceberg ON wrecked it (1.45/16pctDD); partial-TP cut winners (1.79); velo-off sturdier N45 but lower S; real lever = Min room to wall 0.5 (plateau 0.5-0.7) 2.20/34 -> 2.317/32; long-only QQQ uptrend = walk-fwd mandatory"
},
{
"sym": "ETN",
"warn": true,
"pf": 2.305,
"dd": 35.17,
"win": 76.67,
"n": 60,
"arch": "fade-long",
"remicro": false,
"sector": "Single-name",
"family": "fade",
"status": "walk-forward",
"date": "3:33 pm · 20 Jun 2026",
"dateRaw": "2026-06-20T15:33",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R ON · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 18, target-R 1) · Wall-TP ON (min-room 0.3) · Partial-TP ON",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate OFF · Velo OFF",
"note": "long-only clean-fade buf18; 1.47->2.31 @ 35pct DD (caught 2020 crash dip); gate didnt cut DD; high-DD bull-regime; walk-fwd mandatory"
},
{
"sym": "DIA",
"warn": true,
"pf": 2.074,
"dd": 10.94,
"win": 41.94,
"n": 31,
"arch": "fade-long-wall",
"remicro": false,
"sector": "ETF",
"family": "fade",
"status": "walk-forward",
"date": "3:33 pm · 20 Jun 2026",
"dateRaw": "2026-06-20T15:33",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade OFF · Wall-TP ON (min-room 0.5) · Partial-TP OFF",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate OFF · Velo OFF",
"note": "velo seed N=28<floor; dropped velo -> N32 2.02; Min room to wall 0.5 lifts to 2.07/31 (limited room headroom before N floor); partial-TP hurt (1.82); buffer non-binding; long-only Dow uptrend + N=31 near floor = walk-fwd mandatory"
},
{
"sym": "ASML",
"warn": false,
"pf": 2.054,
"dd": 16.44,
"win": 56.76,
"n": 37,
"arch": "fade-both-cascstop-velo",
"remicro": false,
"sector": "Semis",
"family": "fade",
"status": "ready",
"date": "3:33 pm · 20 Jun 2026",
"dateRaw": "2026-06-20T15:33",
"exec": "Take Longs ON · Take Shorts ON · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 0.85, target-R 1) · Wall-TP OFF · Partial-TP OFF",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate OFF · Velo ON (plunge def, window def, dots def)",
"note": "SYMMETRIC edge; long-only seed PF2.26 but N=19<floor; shorts-ON adds trades -> 2.054/DD16.4/N37 (S1.76); CascStop binds buffer but 0.85 is sharp peak (buf3/8 blow DD to 62pct); velo HELPS (off=1.49/N64); wall HURTS (1.42/DD28); clean both-dir = believable not pure bull-fit"
},
{
"sym": "INTC",
"warn": true,
"pf": 2.053,
"dd": 46.6,
"win": 67.35,
"n": 49,
"arch": "fade-long-cascstop",
"remicro": false,
"sector": "Semis",
"family": "fade",
"status": "walk-forward",
"date": "3:33 pm · 20 Jun 2026",
"dateRaw": "2026-06-20T15:33",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 3, target-R 1) · Wall-TP OFF · Partial-TP OFF",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate OFF · Velo OFF",
"note": "structural DOWNTRENDER; long-only only viable (both-dir 0.89/DD44 short-only 0.45); CascStop binds; buf3 = max S (2.053/DD46.6/N49) buf0.85 lower DD36.6 but PF1.12; buf5 DD56 buf15 N10; tight gate cuts DD46->39 but PF2.05->1.56 (S worse); DD46pct = MRVL-tier low quality; walk-fwd mandatory"
},
{
"sym": "SCHD",
"warn": true,
"pf": 2.047,
"dd": 6.73,
"win": 45.71,
"n": 35,
"arch": "fade-long-wall",
"remicro": false,
"sector": "ETF",
"family": "fade",
"status": "walk-forward",
"date": "3:33 pm · 20 Jun 2026",
"dateRaw": "2026-06-20T15:33",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade OFF · Wall-TP ON (min-room 0.3) · Partial-TP OFF",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate OFF · Velo OFF",
"note": "gated seed 3.41/3.85pctDD but N=21<floor; dropped LQX+velo -> clean wall-fade 2.05/35 DD6.73pct; room0.5 & iceberg both hurt; very low DD; long-only div-ETF uptrend = walk-fwd mandatory"
},
{
"sym": "KO",
"warn": false,
"pf": 1.979,
"dd": 19.75,
"win": 53.73,
"n": 201,
"arch": "fade-clean",
"remicro": false,
"sector": "Single-name",
"family": "fade",
"status": "ready",
"date": "3:33 pm · 20 Jun 2026",
"dateRaw": "2026-06-20T15:33",
"exec": "Take Longs ON · Take Shorts ON · Require Min R:R ON · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 18, target-R 1) · Wall-TP ON (min-room 0.3) · Partial-TP ON",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate OFF · Velo OFF",
"note": "clean-fade buffer 18 (plateau 18-25); gates HURT (1.98->1.48); 1.17->1.98; +78pct PnL; low-vol consumer staple = sweet spot"
},
{
"sym": "NXPI",
"warn": false,
"pf": 1.971,
"dd": 20.72,
"win": 65.57,
"n": 61,
"arch": "fade-gated",
"remicro": false,
"sector": "Semis",
"family": "fade",
"status": "ready",
"date": "3:33 pm · 20 Jun 2026",
"dateRaw": "2026-06-20T15:33",
"exec": "Take Longs ON · Take Shorts ON · Require Min R:R ON · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 5, target-R 1) · Wall-TP ON (min-room 0.3) · Partial-TP ON",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate ON (maxLong 0.3, maxShort 0.3, veto 0.6) · Velo ON (plunge 0.25, window 5, dots 1)",
"note": "gate-tighten 0.4->0.3/veto0.6 DOUBLED PF 1.03->1.97 & halved DD 33->21; buffer 5 (semi vol); +99pct PnL; LQX thresholds = 3rd big lever"
},
{
"sym": "VOO",
"warn": true,
"pf": 1.849,
"dd": 12.22,
"win": 60.0,
"n": 30,
"arch": "fade-clean-cascstop",
"remicro": false,
"sector": "ETF",
"family": "fade",
"status": "walk-forward",
"date": "3:33 pm · 20 Jun 2026",
"dateRaw": "2026-06-20T15:33",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 0.85, target-R 1) · Wall-TP OFF · Partial-TP OFF",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate OFF · Velo ON (plunge def, window def, dots def)",
"note": "limited-history ETF (thin N); CascStop binds buffer but default 0.85 optimal (buf18 N=7 / buf5 velo-off DD22pct both worse); wall-fade N=24<floor; seed clean-fade CascStop+velo long-only = best 1.85/30 at exact N floor; borderline N; long-only walk-fwd mandatory"
},
{
"sym": "ADI",
"warn": true,
"pf": 1.836,
"dd": 12.7,
"win": 41.94,
"n": 31,
"arch": "fade-long-wall-gated",
"remicro": false,
"sector": "Semis",
"family": "fade",
"status": "walk-forward",
"date": "3:33 pm · 20 Jun 2026",
"dateRaw": "2026-06-20T15:33",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R ON · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade OFF · Wall-TP ON (min-room 0.3) · Partial-TP OFF",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate ON (maxLong def, maxShort def, veto def) · Velo ON (plunge def, window def, dots def)",
"note": "long-only gated fade-wall seed is best; shorts-on 1.53/N49 worse; gates-OFF clean wall 1.53/16pctDD worse (gates HELP here unlike TSM/AMD); room0.5 N29<floor; CascStop off so buffer non-binding; N=31 near floor; long-only walk-fwd mandatory"
},
{
"sym": "KLAC",
"warn": true,
"pf": 1.823,
"dd": 16.46,
"win": 41.18,
"n": 51,
"arch": "fade-long-wall",
"remicro": false,
"sector": "Semis",
"family": "fade",
"status": "walk-forward",
"date": "3:33 pm · 20 Jun 2026",
"dateRaw": "2026-06-20T15:33",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade OFF · Wall-TP ON (min-room 0.3) · Partial-TP OFF",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate OFF · Velo OFF",
"note": "continuation seed breaker floods 270tr DD31pct; same semi pattern -> fade-wall gates-off best 1.82/DD16/N51; iceberg flat PF but +DD (1.83/DD20); room non-binding; healthy N; long-only walk-fwd mandatory"
},
{
"sym": "MPWR",
"warn": true,
"pf": 1.788,
"dd": 27.21,
"win": 54.84,
"n": 31,
"arch": "fade-long-cascstop-velo-bsl",
"remicro": false,
"sector": "Semis",
"family": "fade",
"status": "walk-forward",
"date": "3:33 pm · 20 Jun 2026",
"dateRaw": "2026-06-20T15:33",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 0.85, target-R 1) · Wall-TP OFF · Partial-TP OFF",
"signals": "Iceberg OFF · BSL/SSL ON (pool def, exh-vol def, eliq OFF) · Breaker OFF",
"gates": "LQX-gate OFF · Velo ON (plunge def, window def, dots def)",
"note": "wall+CascStop seed thins to N25<floor (PF2.84); KEY = drop wall -> plain fade + velo + BSL = N31 PF1.788/DD27.2 (S1.41); CascStop binds buf but 0.85 keeps floor (buf3 better 2.41/DD21 but N29<floor; buf2 N30/DD40); shorts blow DD52; N=31 near floor; long-only walk-fwd mandatory"
},
{
"sym": "PEP",
"warn": false,
"pf": 1.595,
"dd": 6.47,
"win": 48.6,
"n": 107,
"arch": "fade-both",
"remicro": false,
"sector": "Single-name",
"family": "fade",
"status": "ready",
"date": "3:33 pm · 20 Jun 2026",
"dateRaw": "2026-06-20T15:33",
"exec": "Take Longs ON · Take Shorts ON · Require Min R:R ON · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 0.85, target-R 3) · Wall-TP OFF · Partial-TP ON",
"signals": "Iceberg ON (abs 5) · BSL/SSL ON (pool 2, exh-vol 4, eliq OFF) · Breaker ON (vol 7.5)",
"gates": "LQX-gate ON (maxLong 0.5, maxShort 0.15, veto 0.75) · Velo ON (plunge 0.5, window 12, dots 1)",
"note": "user-config reproduced exactly"
},
{
"sym": "TSEM",
"warn": true,
"pf": 1.582,
"dd": 19.19,
"win": 43.59,
"n": 39,
"arch": "continuation-long-wall",
"remicro": false,
"sector": "Semis",
"family": "continuation",
"status": "walk-forward",
"date": "3:33 pm · 20 Jun 2026",
"dateRaw": "2026-06-20T15:33",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY OFF",
"stops": "Stop-beyond-cascade OFF · Wall-TP ON (min-room 0.3) · Partial-TP OFF",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate OFF · Velo OFF",
"note": "TRENDER like XLI; fade thin (long-only N19 PF0.65 / both-dir N28 PF0.90 both <floor); continuation+breaker floods N305 DD41pct; KEY = continuation-WALL (breaker off + Target-OB on) long-only = 1.582/DD19.2/N39; room0.5 worse; shorts-on 0.999/DD38; gates dont help; clean low-DD trender"
},
{
"sym": "SPY",
"warn": true,
"pf": 1.521,
"dd": 8.47,
"win": 37.5,
"n": 32,
"arch": "fade-long-wall",
"remicro": false,
"sector": "ETF",
"family": "fade",
"status": "walk-forward",
"date": "3:33 pm · 20 Jun 2026",
"dateRaw": "2026-06-20T15:33",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade OFF · Wall-TP ON (min-room 1.0) · Partial-TP OFF",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate OFF · Velo ON (plunge def, window def, dots def)",
"note": "WEAK fade name; BSL seed reproduced only 1.06/15pct (not S1 2.02); CascStop+buf25 killed trades (PF0); both-dir 1.35/52; long-only wall-fade + Min room to wall 1.0 (plateau 1.0; 1.5 drops N<30) = best 1.52/32; thin edge but clears PF1; long-only walk-fwd mandatory"
},
{
"sym": "AMD",
"warn": true,
"pf": 1.515,
"dd": 21.31,
"win": 43.75,
"n": 32,
"arch": "fade-long-wall",
"remicro": false,
"sector": "Semis",
"family": "fade",
"status": "walk-forward",
"date": "3:33 pm · 20 Jun 2026",
"dateRaw": "2026-06-20T15:33",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade OFF · Wall-TP ON (min-room 0.3) · Partial-TP OFF",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate OFF · Velo OFF",
"note": "rich continuation seed = DD33pct (breaker 323tr); breaker-off + buf5 raise DD to 38pct; like TSM the fade-wall gates-off velo-off is best 1.52/DD21/N32; tight LQX gate hurts (1.39/DD28/N23); long-only highest-vol semi walk-fwd mandatory"
},
{
"sym": "TXN",
"warn": true,
"pf": 1.455,
"dd": 27.91,
"win": 55.88,
"n": 34,
"arch": "fade-long-cascstop-velo-bsl",
"remicro": true,
"sector": "Semis",
"family": "fade",
"status": "re-microtune",
"date": "3:33 pm · 20 Jun 2026",
"dateRaw": "2026-06-20T15:33",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 0.85, target-R 1) · Wall-TP OFF · Partial-TP OFF",
"signals": "Iceberg OFF · BSL/SSL ON (pool def, exh-vol def, eliq OFF) · Breaker OFF",
"gates": "LQX-gate ON (maxLong 0.5, maxShort def, veto 0.85) · Velo ON (plunge def, window def, dots def)",
"note": "low-vol analog semi; CascStop binds buf but 0.85 = plateau (buf3 1.216/DD37 buf8 PF3/N17<floor); adding velo lifts seed 1.403->1.455 (S 1.104->1.137); BSL HELPS (off 1.295/DD32); tight LQX gate cuts N to 21<floor; LQX-default+velo+BSL = best 1.455/DD27.9/N34; long-only walk-fwd mandatory"
},
{
"sym": "TSM",
"warn": true,
"pf": 1.428,
"dd": 25.2,
"win": 40.0,
"n": 30,
"arch": "fade-long-wall",
"remicro": true,
"sector": "Semis",
"family": "fade",
"status": "re-microtune",
"date": "3:33 pm · 20 Jun 2026",
"dateRaw": "2026-06-20T15:33",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade OFF · Wall-TP ON (min-room 0.3) · Partial-TP OFF",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate OFF · Velo OFF",
"note": "rich continuation seed = DD41pct (breaker floods 322tr); breaker-off continuation 1.43/DD30 N37; tight gates dont cut DD; buf3/8 blow DD to 41pct; fade-wall gates-off = best balance 1.43/DD25/N30; marginal semi N at floor; long-only walk-fwd mandatory"
},
{
"sym": "ARM",
"warn": true,
"pf": 1.366,
"dd": 31.6,
"win": 33.33,
"n": 114,
"arch": "continuation-long-breaker",
"remicro": true,
"sector": "Semis",
"family": "continuation",
"status": "re-microtune",
"date": "3:33 pm · 20 Jun 2026",
"dateRaw": "2026-06-20T15:33",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY OFF",
"stops": "Stop-beyond-cascade OFF · Wall-TP OFF · Partial-TP OFF",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker ON (vol def)",
"gates": "LQX-gate OFF · Velo OFF",
"note": "recent-IPO thin name; fade-wall best PF 1.61 but N=20<floor (plain-fade N18 PF0.98); only continuation+breaker clears N>=30; long-only 1.366/DD31.6/N114 beats both-dir 1.128/DD40; tight LQX gate HURTS (1.293 same DD); high-DD thin-history walk-fwd mandatory"
},
{
"sym": "XLI",
"warn": true,
"pf": 1.298,
"dd": 12.51,
"win": 40.0,
"n": 50,
"arch": "continuation-long-wall",
"remicro": true,
"sector": "ETF",
"family": "continuation",
"status": "re-microtune",
"date": "3:33 pm · 20 Jun 2026",
"dateRaw": "2026-06-20T15:33",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY OFF",
"stops": "Stop-beyond-cascade OFF · Wall-TP ON (min-room 0.3) · Partial-TP OFF",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate OFF · Velo ON (plunge def, window def, dots def)",
"note": "STUBBORN; fade regime FAILS (0.95/27); breaker bloats to 320tr PF1.0 DD24pct; LQX tight gate hurts (1.03/25); room0.6 worse; continuation-wall seed is best but thin 1.30/50; clears PF1 + N floor; long-only industrials uptrend = walk-fwd mandatory"
},
{
"sym": "TLT",
"warn": false,
"pf": 1.272,
"dd": 17.66,
"win": 48.78,
"n": 205,
"arch": "fade-clean",
"remicro": true,
"sector": "ETF",
"family": "fade",
"status": "re-microtune",
"date": "3:33 pm · 20 Jun 2026",
"dateRaw": "2026-06-20T15:33",
"exec": "Take Longs ON · Take Shorts ON · Require Min R:R ON · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 30, target-R 1) · Wall-TP ON (min-room 0.3) · Partial-TP ON",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate OFF · Velo OFF",
"note": "CLEAN cascade-fade; buffer sweep 30 (plateau 30-35) beats user-22 1.232->1.272 same DD; +18.05pct PnL; commit-fix made numeric sweeps real"
},
{
"sym": "MU",
"warn": true,
"pf": 1.239,
"dd": 13.86,
"win": 61.29,
"n": 31,
"arch": "fade-long-velo-nowall",
"remicro": true,
"sector": "Semis",
"family": "fade",
"status": "re-microtune",
"date": "3:33 pm · 20 Jun 2026",
"dateRaw": "2026-06-20T15:33",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade OFF · Wall-TP OFF · Partial-TP OFF",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate OFF · Velo ON (plunge def, window def, dots def)",
"note": "continuation+breaker seed floods N372 DD60pct; WALL HURTS MU (fade-wall 0.78/N28 / cont-wall 0.92/DD35); KEY = plain fade no-wall + velo long-only = clean 1.239/DD13.9/N31; velo essential (off=0.978); shorts hurt (0.90); CascStop off; N=31 near floor; long-only walk-fwd mandatory"
},
{
"sym": "NVDA",
"warn": true,
"pf": 1.185,
"dd": 34.04,
"win": 32.88,
"n": 222,
"arch": "continuation-long-breaker-gated",
"remicro": true,
"sector": "Semis",
"family": "continuation",
"status": "re-microtune",
"date": "3:33 pm · 20 Jun 2026",
"dateRaw": "2026-06-20T15:33",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R ON · Cascade-Fade ONLY OFF",
"stops": "Stop-beyond-cascade OFF · Wall-TP OFF · Partial-TP OFF",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker ON (vol def)",
"gates": "LQX-gate ON (maxLong 0.3, maxShort def, veto 0.6) · Velo ON (plunge def, window def, dots def)",
"note": "marginal; fade-wall N<30 always (gated 1.09/N19 / clean 0.87/N31<PF1); continuation floods N>200 at DD34pct; long-only+tight-gate(ML0.3/veto0.6) best S 1.185/DD34/N222; both-dir 1.085/DD38; gates barely cut DD (TSM/AMD pattern); high-vol high-DD walk-fwd mandatory"
},
{
"sym": "MRVL",
"warn": false,
"pf": 1.134,
"dd": 43.59,
"win": 35.38,
"n": 212,
"arch": "fade",
"remicro": true,
"sector": "Semis",
"family": "fade",
"status": "re-microtune",
"date": "3:33 pm · 20 Jun 2026",
"dateRaw": "2026-06-20T15:33",
"exec": "Take Longs ON · Take Shorts ON · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade OFF · Wall-TP ON (min-room def) · Partial-TP ON",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate ON (maxLong 0.6, maxShort 0.6, veto 0.85) · Velo OFF",
"note": "DEEP COULD NOT BEAT S1; extreme-vol semi; deep best only 0.9/61 (gate0.3); loose gate=83pct DD tight=low PF; S1 1.134 stands but 44pct DD=low quality; DEFER not clean edge"
},
{
"sym": "QCOM",
"warn": true,
"pf": 1.076,
"dd": 21.93,
"win": 23.68,
"n": 38,
"arch": "fade-long-wall-gated",
"remicro": true,
"sector": "Semis",
"family": "fade",
"status": "re-microtune",
"date": "3:33 pm · 20 Jun 2026",
"dateRaw": "2026-06-20T15:33",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade OFF · Wall-TP ON (min-room 0.3) · Partial-TP OFF",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate ON (maxLong 0.4, maxShort def, veto 0.7) · Velo ON (plunge def, window def, dots def)",
"note": "rich continuation+breaker seed floods N308/DD35; long-only fade-wall+velo best (plain-fade 1.063/DD23.5/N45 / fade-wall gates-off 1.122/DD26/N43); velo HELPS (off DD32); loose LQX gate 0.4/0.7 cuts DD26->22 PF~flat = best quality 1.076/DD22/N38; tight 0.3/0.6 over-trims (1.042); marginal edge; long-only walk-fwd mandatory"
},
{
"sym": "MCHP",
"warn": true,
"pf": 1.048,
"dd": 37.23,
"win": 27.38,
"n": 84,
"arch": "continuation-long-wall",
"remicro": true,
"sector": "Semis",
"family": "continuation",
"status": "re-microtune",
"date": "3:33 pm · 20 Jun 2026",
"dateRaw": "2026-06-20T15:33",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY OFF",
"stops": "Stop-beyond-cascade OFF · Wall-TP ON (min-room 0.3) · Partial-TP OFF",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate OFF · Velo OFF",
"note": "marginal; continuation+breaker seed floods N384/DD51 (both-dir) N304/DD50 (long); plain-fade clean 0.805/DD15 but PF<1; fade-wall 0.495; KEY = continuation-WALL long-only velo/BSL OFF = 1.048/DD37.2/N84 (velo+BSL pulled it to 0.958); tight gate on breaker barely cuts DD (48); weak edge DD37 walk-fwd mandatory"
},
{
"sym": "AMAT",
"warn": false,
"pf": 0.944,
"dd": 41.24,
"win": 31.71,
"n": 41,
"arch": "fade-long-wall",
"remicro": true,
"sector": "Semis",
"family": "fade",
"status": "re-microtune",
"date": "3:33 pm · 20 Jun 2026",
"dateRaw": "2026-06-20T15:33",
"exec": "Take Longs ON · Take Shorts OFF · Require Min R:R OFF · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade OFF · Wall-TP ON (min-room 0.3) · Partial-TP OFF",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate OFF · Velo OFF",
"note": "NON-EDGE 4h; N>=30 configs ALL PF<1 (fade-wall CascStop buf0.85 0.878/DD44/N38 / plain fade-wall 0.944/DD41/N41); PF>1 configs ALL N<floor (CascStop buf5+wall 1.797/DD38/N20 / buf8 1.442/N19 / no-wall buf8 1.859/DD57/N22); continuation+breaker DD83pct N410; cannot clear PF1 AND N30 simultaneously; DD structurally 38-44pct; defer like MRVL"
},
{
"sym": "XLF",
"warn": false,
"pf": 0.895,
"dd": 36.32,
"win": 37.5,
"n": 152,
"arch": "fade",
"remicro": true,
"sector": "ETF",
"family": "fade",
"status": "re-microtune",
"date": "3:33 pm · 20 Jun 2026",
"dateRaw": "2026-06-20T15:33",
"exec": "Take Longs ON · Take Shorts ON · Require Min R:R ON · Cascade-Fade ONLY ON",
"stops": "Stop-beyond-cascade ON (buffer 20, target-R 1) · Wall-TP ON (min-room 0.3) · Partial-TP ON",
"signals": "Iceberg OFF · BSL/SSL OFF · Breaker OFF",
"gates": "LQX-gate OFF · Velo OFF",
"note": "NON-EDGE 4h; tried fade 0.895/36 continuation-breaker 0.576/74 filtered-fade 0.913/42 tight-buf3 0.668/57; DD structurally >=36pct; financials misfit; FLAG owner for any manual config"
}
];
window.DEEP_STATS = {"count": 36, "universe": 52, "pending": 16, "ready": 4, "walkfwd": 20, "remicro": 12, "above15": 24, "topPF": 5.748, "topSym": "DE", "cleanestDD": 6.47, "cleanestSym": "PEP", "fade": 30, "continuation": 6, "date": "3:33 pm · 20 Jun 2026", "dateRaw": "2026-06-20T15:33", "sect": {"ETF": {"n": 11, "meanPF": 2.25, "best": 4.533, "bestSym": "GLD", "ready": 8}, "Semis": {"n": 18, "meanPF": 1.63, "best": 3.837, "bestSym": "LRCX", "ready": 9}, "Single-name": {"n": 7, "meanPF": 3.19, "best": 5.748, "bestSym": "DE", "ready": 7}}};
